### ISSUE TITLE
Add chain() method for all stream types

### ISSUE THREAD

**Issue by amaembo** [amaembo/streamex#10]
As suggested in [JDK-8140283](https://bugs.openjdk.java.net/browse/JDK-8140283) a chain method could be added to all stream types which maps the current stream to the result of the specified function:

    <U> chain(Function<? super StreamEx<T>,U> func) {
        return func.apply(this);
    }

This would allow enhancing the streams with custom processing method while keeping the chaining syntax.

It's better to stay in sync with the JDK-8140283 in order not to produce name/signature clash with future Java versions.

* [x] Implementation
* [x] JavaDoc
* [x] Fix JavaDoc bug for generic parameter if necessary
* [x] Tests
* [x] Changes
* [x] Cheatsheet

**Comment by nathanila** [comment]
I'm loving chain()!  I just realized that chain() can be used as an intermediate or terminal operator.
