### ISSUE TITLE
SkipUntil

### ISSUE THREAD

**Issue by sophiahawes** [amaembo/streamex#102]
Would it be possible to add a StreamEx method to skipUntil a predicate is met. That combined with takeUntil would make a powerful streaming operation.

**Comment by nbardiuk** [comment]
Hi @sophiahawes 
Looks like `skipUntil(predicate)` is the same as [`dropWhile(predicate.negate())`](https://github.com/amaembo/streamex/blob/master/src/main/java/one/util/streamex/AbstractStreamEx.java#L1740)

**Comment by sophiahawes** [comment]
Perfect. Thank you. I somehow missed that :)
