### ISSUE TITLE
last() on stream

### ISSUE THREAD

**Issue by elect86** [amaembo/streamex#103]
Hi Tagir,

awesome library!

Anyway, I always missed a simple `last()` method to retrieve the last element of a stream

Actually I am doing 

`.reduce((a, b) -> b).orElse(null)`

Would it be possible?

**Comment by amaembo** [comment]
Hello! Thank you for your interest towards my library. Unfortunately I must decline your request. The `orElse(null)` part is completely against the rest of the API which always returns `Optional` (not null) when value could be empty. Without `orElse(null)` the remaining thing is `.reduce((a, b) -> b)` which is not much longer compared to possible alternative `.findLast()` (you save less than 10 characters). Given the fact that looking for the last stream element is not very common demand I don't see the necessity to pollute API with the new method. Remember that we have `IntStreamEx`, `LongStreamEx`, `DoubleStreamEx`, `StreamEx` and `EntryStream`, so every new method should be added to all of these methods.

Note that there's also an alternative like this:

~~~~java
import static one.util.streamex.MoreCollectors.*;

myStream.collect(last()).orElse(null);
~~~~

By the way why you need last stream element so often? Could you specify some common use cases when it's necessary?

**Comment by elect86** [comment]
I am working on a small rendering engine and since I want to be efficient, I have incremental modifications (i.e: grab the last mesh added to a flat list and add it to my graphic pipeline)

It's not oft, it's not vital, it was just a tiny wish since we are talking about a stream enhancing lib

I totally understand if you want to avoid pollution, anyway since we have `findFirst()` another reason to have a `findLast()` may be symmetry

**Comment by amaembo** [comment]
I see. Note that I already have shortcuts like `findFirst(condition)` which is `filter(condition).findFirst()`, so for symmetry I will need to add such versions to `findLast` as well (to all Stream implementations) adding even more API methods. 

`findFirst()` is special as it can short-circuit, so it cannot be expressed in terms of `reduce((a, b) -> a)` (which is not short-circuiting op). As Java Stream is left-to-right by nature, it cannot skip elements for `findLast()` (though some special kind of optimization is probably possible for parallel streams). It was suggested by Stuart Marks to support "reversible streams" (see comment [here](https://bugs.openjdk.java.net/browse/JDK-8133680)), in which case `findLast()` would be more sensible, but nobody worked on this change. Such change would require support from stream source: almost all collection sources like `ArrayList` or `LinkedList` are easily reversible (can be traversed right-to-left), also operations like `Stream.concat` can be adapted to be reversible. But without support from JDK it's hard for me to make this optimization in the library. If I introduce `findLast()` method, some users might think that it will optimize the traversal actually reading the last element only, and will be unpleasantly surprised to know that the whole input collection is being processed. So here explicit `reduce((a, b) -> b)` would be less confusing as it's clear that the whole input will be processed.

Probably instead it's better to create special stream constructors for sources like `List` (assuming the list is random-access) or array like this:

~~~~java
StreamEx.ofReversed(list).filter(...).findFirst();
StreamEx.ofReversed(array).filter(...).findFirst();
~~~~

It would be more efficient and would add more features for free. For example, if you want to select last N elements satisfying the condition, you can use `StreamEx.ofReversed(list).filter(...).limit(n).toList()`.

Note that proposed `StreamEx.ofReversed(list)` can be easily expressed via stream of indices like this: `IntStreamEx.rangeClosed(list.size()-1, 0, -1).elements(list)`, so you can use it right now.
