### ISSUE TITLE
IntStreamEx.of(IntBuffer)

### ISSUE THREAD

**Issue by elect86** [amaembo/streamex#108]
Hi Tagir,

since in jogl I am gonna handle GL resources through `IntBuffer`s, it'd be nice to have the possibility to init a `StreamEx` from those

**Comment by amaembo** [comment]
Sounds interesting. Will think about it. Similarly `LongStreamEx.of(LongBuffer)` could be implemented. Note however that buffer has internal state like current position and limit. I think the StreamEx implementation should not alter the state of the supplied buffer.

**Comment by elect86** [comment]
`LongBuffer` is not interesting but you can implement for it too if you want.

Jogl already avoid any internal state modification by creating/deleting resource at the given position buffer. For this purpouse there is `put(int index, int value)`

**Comment by amaembo** [comment]
It seems that simplest implementation would be like `IntStreamEx.range(buf.position(), buf.limit()).map(buf::get)`. You may check whether it works for you.

**Comment by elect86** [comment]
Yep and it'd be cool to have also just a simple `IntStreamEx.range()`, anyway I'd like something like:

`IntStreamEx.of(textureName).forEach(...)`

**Comment by amaembo** [comment]
IntStreamEx.of(IntBuffer), LongStreamEx.of(LongBuffer), DoubleStreamEx.of(DoubleBuffer) are implemented. Current implementation is quite straight-forward, but it should be quite fast.

**Comment by elect86** [comment]
Awesome, thanks Tagir! :+1:
