### ISSUE TITLE
joining() Returns Non-empty String for empty Stream

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#109]
The documentation for `joining(CharSequence delimiter, CharSequence prefix, CharSequence suffix)` says 

> Returns:
>    a String. For empty input stream empty String is returned.

However, this code returns a String with 1 space in it.

```
      StreamEx.
         of("").
         remove(String::isEmpty).
         joining("", " ", "");
```

This code also returns a String with 1 space in it.

```
      StreamEx.
         of("").
         remove(String::isEmpty).
         joining("", "", " ");
```

Please fix joining() so that it returns an empty String for an empty stream.

**Comment by amaembo** [comment]
The problem is in documentation, not in the implementation. Prefix and suffix should be also added even for empty stream. For example, `StreamEx.empty().joining("", "[", "]")` should return `"[]"`, not empty string. I will update the documentation, thank you for your report.
