### ISSUE TITLE
notSelect()

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#113]
I've used the select() method a lot.  I just ran into a case where notSelect() would be useful.

```
List<JMenuItem> list;

...

StreamEx.
   of(list).
   notSelect(JMenu.class).
   ...
```

Can you consider adding notSelect()?  The work around is to do the following...

```
StreamEx.
   of(list).
   remove(item -> item instanceof JMenu).
   ...
```

I suppose the work around is easy enough.  I understand that select() must exist so that the generic type of the stream can be changed.  notSelect() doesn't require a generic type change and hence may not be worth adding.

**Comment by amaembo** [comment]
Hello!

Note that you can write even shorter: `StreamEx.of(list).remove(JMenu.class::isInstance)`. So basically dedicated `notSelect` method would save you only 9 characters. I don't think it's worth adding.
