### ISSUE TITLE
StreamEx.of(enum)?

### ISSUE THREAD

**Issue by elect86** [amaembo/streamex#114]
Hi Tagir,

would it be possible to have `StreamEx.of(enum)`? Or given we have `values()`, it makes it no sense?

**Comment by amaembo** [comment]
Thank you for your suggestion. Another alternative is StreamEx.of(EnumSet.allOf(enum.class)). Adding an overload for StreamEx.of(Class<? extends Enum<?>>) is not a good idea as its erasure is simply StreamEx.of(Class) which may cause compatibility problems in future. Actually there are already too many overloads for StreamEx.of. It's possible to name method differently like StreamEx.allOf, but given existing alternatives I don't think that it's necessary.
