### ISSUE TITLE
Filter method with extractor

### ISSUE THREAD

**Issue by isopov** [amaembo/streamex#117]
Inspired by `java.util.Comparator#comparing(java.util.function.Function<? super T,? extends U>, java.util.Comparator<? super U>)`

It is frequent for me to use Stream is in the following manner:
````
stream.filter(i -> booleanReturningMethod(i.getSomething()))...
````
It will be cool, IMO, to be able to write it as
````
streamEx.filter(MyClass::getSomething, Util::booleanReturningMethod)...
````

In order to do this somethig similar to `Comparator.comparing` method is needed. Is this desire is normal enough for implementing and making a PR?

**Comment by amaembo** [comment]
Sorry, I think I should decline this feature for at least two reasons:

1. It does not add any functionality and convenience in general. The "cool" version in your example is actually longer. I can think up the case where it will become shorter, but it's rare case.
2. It's not more readable. Think about somebody who sees this code for the first time. What two parameters mean? Are these two predicates which both have to be true? Or function composition like you propose? In contrast current version `i -> booleanReturningMethod(i.getSomething())` is not confusing: composition is evident here.
3. I have tons of filtering methods. To name a few: `IntStreamEx.filter`, `LongStreamEx.filter`, `DoubleStreamEx.filter`, `StreamEx.remove` (and primitive friends), `EntryStream.filterKeys`, `EntryStream.filterValues`, `EntryStream.filterKeyValue`, `MoreCollectors.filtering` and so on. Methods like `anyMatch` also receive predicate. Should I update all of them to make two-argument overload for consistency?
4. If you really like method references, it's not very difficult to write combinators in your code like this (PECS omitted for brevity):

~~~~java
public class Predicates {
  public static <K, T> Predicate<T> compose(Function<T, K> fn, Predicate <K> pred) {
    return t -> pred.test(fn.apply(t));
  }

  public static <T> Predicate<T> and(Predicate<T> pred1, Predicate <K> pred2) {
    return pred1.and(pred2);
  }
}
~~~~

This way the resulting code would be clear:
`streamEx.filter(compose(MyClass::getSomething, Util::booleanReturningMethod))`
or
`streamEx.filter(and(Util::anotherBooleanMethod, Util::booleanReturningMethod))`

**Comment by isopov** [comment]
Thanks for detailed explanation. Util class is a good way to go too!
