### ISSUE TITLE
EntryStream.distinctKeys(int count)

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#120]
StreamEx has a method called distinct(int atLeast).  I would like EntryStream to have a similar method called distinctKeys(int atLeast).

Consider the following code.

```
IntStreamEx.
    range(titles.size()).
    mapToEntry(titles::get, Integer::valueOf).
    distinctKeys(2).
    grouping();
```

This would create a Map<String, List<Integer>> where List<Integer> is of size 2 or more.  It would eliminate all of the List<Integer> of size 1.

**Comment by amaembo** [comment]
Thanks for the suggestion. Sounds reasonable as it cannot be easily expressed using existing operations, but can be easily implemented using internal (not exposed) APIs. Will do it.

**Comment by amaembo** [comment]
Mmm... Actually after rereading your request I'm in doubt. Currently existing `distinct(long atLeast)` does not preserve all elements which appear atLeast times. It preserves only one (arbitrary element) of them. So in your case if I implement `distinctKeys(2)` in the same way, it will also keep only one (arbitrary) element of the stream with given key. So your sample would produce only lists of size 1.

Your problem could be solved like this

~~~~java
Map<String, List<Integer> map = IntStreamEx.
    range(titles.size()).
    mapToEntry(titles::get, Integer::valueOf).
    grouping();
map.values().removeIf(list -> list.size() < 2);
~~~~

The operation you want might need substantial buffering. Also it will surely change the order of elements in the stream in hard-to-predict order. Finally it should not be named as `distinctKeys()` as the keys in the resulting stream will not be distinct.

So I can implement `distinctKeys` in the way it seems logical (to return only objects with distict keys which appear at least n times), but now I'm not sure whether it's a useful feature. Alternatively I can think about implementing the feature you actually want, but I'm still in doubts: how to name it and whether it's actually better than existing solution with `removeIf` (performancewise, I guess, `removeIf` should be better).

**Comment by nathanila** [comment]
Thank you for the suggested solution.  I hadn't thought about removeIf().  I'll see where that makes sense to do in the several places I am needing this solution.

As for the name of the method, maybe we can use a word from SQL: having.

There are two things to consider when creating a new API: maintainability and performance.  The most expensive thing about software is engineering time to write and maintain the code.  So, if a new API makes it easier to write and maintain code, then it is worth adding even if it doesn't improve performance.
