### ISSUE TITLE
Adding sample documentation?

### ISSUE THREAD

**Issue by wafisher** [amaembo/streamex#121]
Would it be possible to add sample documentation for some of the operations? Think simple examples that elucidate the operation. For example:

#### `StreamEx.cross()`
Example: `StreamEx.of(1, 2).cross(4, 5) -> {1,4}, {1, 5}, {2, 4}, {2, 5}`.

I feel like either the cheatsheet or the Javadoc should have this. It allows the user (at least myself) to grok/test the concept almost immediately. Happy to start submitting documentation!

**Comment by amaembo** [comment]
Added. Feel free to suggest samples for other operations (much better in the form of pull requests!)
