### ISSUE TITLE
Add Try monad

### ISSUE THREAD

**Issue by Xaerxess** [amaembo/streamex#125]
When dealing with exceptions in streams, I started to see the lack of `Try` monad ([Scala has one](http://www.scala-lang.org/api/2.12.0/scala/util/Try.html), and [so does Javaslang](http://www.javaslang.io/javaslang-docs/#_try), there are also [independent projects implementing one](https://github.com/jasongoodwin/better-java-monads)). 

Because I don't want to move to Javaslang (yet) (their own collections framework to be specific), I wonder if you'd be interested in having `Try` in StreamEx.

**Comment by amaembo** [comment]
Thank you for your suggestion and for your interest to my library. Unfortunately having Try monad (also Either monad, etc.) is out of the scope of StreamEx library. The goal of the library is to extend the Java 8 Stream API only, so it's concentrated only on extending Streams and adding new Collectors. It's not a general purpose make-java-look-like-haskell library. 

If you don't like Javaslang (I don't like it either), there are some tinier implementations like [here](https://github.com/jasongoodwin/better-java-monads) which concentrate on monads only.

**Comment by Xaerxess** [comment]
Thanks for quick feedback, I'll examine `better-java8-monads`.
