### ISSUE TITLE
Add "abbreviate" method

### ISSUE THREAD

**Issue by seidler2547** [amaembo/streamex#126]
I have looked over the Cheatsheet but I did not find this: I would love this functionality that limits a stream, but appends an item or replaces the last item when the limit was reached. Some examples, two possible ways of implementation:
*Option A*:
```
Stream.of("a", "b", "c", "d").abbreviate(2, "z") == "a", "z"
Stream.of("a", "b", "c", "d").abbreviate(3, "z") == "a", "b", "z"
Stream.of("a", "b", "c", "d").abbreviate(4, "z") == "a", "b", "c", "d"
Stream.of("a", "b", "c", "d").abbreviate(5, "z") == "a", "b", "c", "d"
```
or *Option B*:
```
Stream.of("a", "b", "c", "d").abbreviate(2, "z") == "a", "b", "z"
Stream.of("a", "b", "c", "d").abbreviate(3, "z") == "a", "b", "c", "z"
Stream.of("a", "b", "c", "d").abbreviate(4, "z") == "a", "b", "c", "d"
Stream.of("a", "b", "c", "d").abbreviate(5, "z") == "a", "b", "c", "d"
```
Option A could even be called `limit` as the additional parameter would distinguish it from the normal limit.

**Comment by amaembo** [comment]
Thank you for your interest to my library. Currently your problem could be solved using `headTail/chain`:

```java
// In some utility class
private static <T> StreamEx<T> abbreviate(StreamEx<T> stream, long limit, T ellipsis) {
    return stream.headTail((head, tail) -> limit <= 0 ? StreamEx.of(ellipsis) :
        abbreviate(tail, limit-1, ellipsis).prepend(head));
}

public static <T> UnaryOperator<StreamEx<T>> abbreviate(long limit, T ellipsis) {
    return s -> abbreviate(s, limit, ellipsis);
}

// Test code
System.out.println(StreamEx.of("a", "b", "c", "d").chain(abbreviate(0, "z")).toList());
System.out.println(StreamEx.of("a", "b", "c", "d").chain(abbreviate(1, "z")).toList());
System.out.println(StreamEx.of("a", "b", "c", "d").chain(abbreviate(2, "z")).toList());
System.out.println(StreamEx.of("a", "b", "c", "d").chain(abbreviate(3, "z")).toList());
System.out.println(StreamEx.of("a", "b", "c", "d").chain(abbreviate(4, "z")).toList());
System.out.println(StreamEx.of("a", "b", "c", "d").chain(abbreviate(5, "z")).toList());
```

The output is:

```
[z]
[a, z]
[a, b, z]
[a, b, c, z]
[a, b, c, d]
[a, b, c, d]
```

In general, the problem looks too specific. Why you need this? If you just want to prettify printing, could it be solved using the `Joining` collector instead?

```java
System.out.println(StreamEx.of("a", "b", "c", "d").collect(
        Joining.with(", ").maxChars(7).cutAfterDelimiter().ellipsis("z")));
```

Output:

```
a, b, z
```

**Comment by seidler2547** [comment]
Well sometimes limiting by character count is not the requirement, rather by item count. It will also facilitate things like "You have selected items 'Item 1', 'Item 2', ..., 'Item 200'".

Another use case for us is Excel Export where we want to insert a notice in the last row that more than the maximum allowed rows are not being exported. Nothing that couldn't be solved otherwise, it just would be very clean to have it in the Stream itself.

Is the performance of the `headTail/chain` solution good, e.g. for long streams that are being limited?

**Comment by amaembo** [comment]
@seidler2547 it's a little bit slower, but if you have an Excel export in the next line, you should not actually care.

**Comment by amaembo** [comment]
Btw how would you implement `'Item 1', 'Item 2', ..., 'Item 200'` using hypothetical `abbreviate` method?

**Comment by amaembo** [comment]
I added Joining.maxElements() (#164), so now it's possible to use Joining collector, adding an ellipsis when specific number of elements (not specific string length) is reached. Given this and ability to express the generic abbreviate operation with `headTail`, I think this issue could be closed.
