### ISSUE TITLE
add filterBy() shortcut methods

### ISSUE THREAD

**Issue by mmariotti** [amaembo/streamex#127]
Hi,
first of all, I really want to thank you, your work is wonderful.

Back to the topic, I meet this scenario very often:

    StreamEx.of(persons)
        .filter(p -> Objects.equals(p.getProperty(), someValue))
        ...

but I'd like to write:

    StreamEx.of(persons)
        .filterBy(Person::getProperty, someValue)
        ...

I already created my utils class so that I can:

    StreamEx.of(persons)
        .filter(Predicates.filterBy(Person::getProperty, someValue))
        ...

But it's still cumbersome.
So, I'm asking to add to `AbstractStreamEx` the following shortcut methods (maybe the 2nd and 3rd are too specific):

    public <R> S filterBy(Function<? super T, R> mapper, R value)
    {
        return filterBy(mapper, value, Objects::equals);
    }

    public <R> S filterBy(Function<? super T, R> mapper, R value, BiPredicate<R, R> predicate)
    {
        return filter(x -> predicate.test(mapper.apply(x), value));
    }

    public <R> S filterBy(Function<? super T, R> mapper, Predicate<? super R> predicate)
    {
        return filter(x -> predicate.test(mapper.apply(x)));
    }

Thank you, and keep up the excellent work.

**Comment by amaembo** [comment]
I don't like adding 2nd and 3rd case (see also #117), but first one seems to be quite common case. It's usually unnecessary for primitive streams and for `anyMatch` can be easily expressed via `map(mapper).has(value)`, so there's no obligation to add the corresponding versions for other methods consuming predicate. Also unlike 2nd and 3rd case this may actually add usefulness if you want to compare with value which is not effectively-final, so you cannot write `filter(t -> t.getSomething().equals(v))` without reassigning `v` to intermediate final variable. 

I will implement it, though I will add it in StreamEx now, not in AbstractStreamEx. I doubt it's too useful for `EntryStream` in this form and don't want to pollute its API unnecessarily. If we find it useful, we can pull it up later.

**Comment by mmariotti** [comment]
Thank you!!
