### ISSUE TITLE
EntryStream.sorted()

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#129]
Calling sorted() on an EntryStream<String, String> throws the following exception:

> Exception in thread "main" java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.lang.Comparable
> 	at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47)
> 	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
> 	at java.util.TimSort.sort(TimSort.java:220)
> 	at java.util.Arrays.sort(Arrays.java:1512)
> 	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:348)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at one.util.streamex.AbstractStreamEx.forEach(AbstractStreamEx.java:356)
> 	at one.util.streamex.EntryStream.forKeyValue(EntryStream.java:1345)

Please change sorted() to sort by the HashMap key first and then by value.

**Comment by amaembo** [comment]
Sorry, but I cannot fix this as it would break the contract of the `Stream` interface the `EntryStream` class implements. See [the specification](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#sorted--):

> Returns a stream consisting of the elements of this stream, sorted according to natural order. If the elements of this stream are not `Comparable`, a `java.lang.ClassCastException` may be thrown when the terminal operation is executed. 

As `EntryStream` implements `Stream`, it must obey its contract. Here as stream elements (entries of `HashMap`) are not `Comparable`, no sorting could be performed. If you have your custom map implementation which produces comparable entries, then `EntryStream.sorted()` will work.

You may enforce custom sorting order supplying your own comparator (e.g. `Map.Entry.comparingByKey().thenComparing(Map.Entry::getValue)`).
