### ISSUE TITLE
ofCombination(int n, int k)

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#131]
StreamEx has a method called ofPermutation(int) but not ofCombination(int n, int k).  Please consider adding this method.  Here's some code which implements this.

```
   public static StreamEx<int[]> ofCombinations(int n, int k)
   {
      StreamEx<int[]> result;
      Combine combine;

      Preconditions.verifyArgument(n >= 0, "n < 0 : %d", n);
      Preconditions.verifyArgument(k >= 0, "k < 0 : %d", k);

      combine = new Combine(n, k);
      result  = StreamEx.of(combine);

      return(result);
   }

   private static class Combine extends AbstractSpliterator<int[]>
   {
      private final int m_indexes[];
      private final int m_n;

      public Combine(int n, int k)
      {
         super(choose(n, k), DISTINCT | IMMUTABLE | NONNULL | ORDERED | SIZED | SUBSIZED);

         m_n = n;

         m_indexes = IntStreamEx.
            range(k).
            toArray();
      }

      private static long choose(long n, long k)
      {
         long result, div, gcd, t;

         if (k > n)
            return(0);

         result = 1;

         for (div = 1; div <= k; ++div, --n)
         {
            gcd     = gcd(result, div);
            result /= gcd;
            t       = n / (div / gcd);

            if (result > Long.MAX_VALUE / t)
               return(Long.MAX_VALUE);

            result *= t;
         }

         return(result);
      }

      private static long gcd(long x, long y)
      {
         long t;

         while (y != 0)
         {
            t = x % y;
            x = y;
            y = t;
         }

         return(x);
      }

      @Override
      public boolean tryAdvance(Consumer<? super int[]> action)
      {
         int i, indexes[];

         if (m_indexes[m_indexes.length - 1] >= m_n)
            return(false);

         indexes = m_indexes.clone();

         action.accept(indexes);

         for (i = m_indexes.length; --i >= 0; )
            if (++m_indexes[i] < m_n)
               break;

         while (++i < m_indexes.length)
            m_indexes[i] = m_indexes[i - 1] + 1;

         return(true);
      }
   }
```

**Comment by amaembo** [comment]
Thank you for your suggestion. Is it possible to support parallelization easily? In PermutationSpliterator I just track the remaining size and can recreate an array from the remaining size in trySplit.

Is this feature actually useful for you or you just want to add it for completeness? I even had doubts about usefulness of `ofPermutations`...

**Comment by nathanila** [comment]
As for parallelization, there is an algorithm out there that can turn an index into a specific combination or permutation (I can't remember for which).  Thus, one simply has to pick an index to start the next split.

ofPermutations() is actually useful for me.  I implemented the code in my own class and I am using it.

**Comment by nathanila** [comment]
[Here](https://bitbucket.org/rayortigas/everyhand-java/src/9e5f1d7bd9ca/src/Combinatorics.java?fileviewer=file-view-default) is some better code which uses a simple int to hold the combination instead of an int[].  The limitation is that only sets of 32 elements can be dealt with.  I suppose one could use long instead and thus 64 elements can be dealt with.  I would hope 64 elements would be sufficiently large.

As for parallelization, this is easy.  Just pick a number which is larger and has the same number of bits set to 1.  The following wouldn't be a perfect split in half, but simply executing "next << 1" would give you a quick and dirty split.

**Comment by amaembo** [comment]
I would not limit the combination size. Unlike permutation which number grows very fast, number of combinations could be small even for larger n and k. For example, `n = 100, k = 99` (only 100 different combinations).

**Comment by amaembo** [comment]
This code does not seem to work well. I tried `ofCombinations(5, 3).map(Arrays::toString).forEach(System.out::println);` and see:

```
[0, 1, 2]
[0, 1, 3]
[0, 1, 4]
[0, 2, 3]
[0, 2, 4]
[0, 3, 4]
```

Which is clearly not all possible combinations.

**Comment by amaembo** [comment]
I made preliminary implementation with proper splitting: I reinvented a ~wheel~ method to get a combination by its index. Currently CNK(n, k) > Long.MAX_VALUE is not supported (this could be done via separate spliterator which uses poor man splitting, but I don't know whether it's useful). 

Note to self: JavaDoc, CHANGES.md, CHEATSHEET.md should be updated.
