### ISSUE TITLE
StreamEx to implement nonNull()

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#133]
I posted this [question](http://stackoverflow.com/questions/40774367/eclipse-external-null-annotation-for-abstractstreamex-nonnull) on StackOverflow.  I figured out a solution, but I need some help.  If StreamEx were to implement nonNull(), then the solution would be easy.  In other words, please add the following to StreamEx...

```
   public StreamEx<T> nonNull() {
      return(super.nonNull());
   }
```

With the above code in place, I can then write the following in StreamEx.eea.

```
nonNull
 ()Lone.util.streamex.StreamEx<TT>;
 ()L1one.util.streamex.StreamEx<T1T>;
```

I am not sure if EntryStream needs to do likewise and implement nonNull().  If this would mean that the Map.Entry's would be guaranteed to be non-null instead of the keys and values, then I don't know how useful nonNull() is.

**Comment by amaembo** [comment]
I'm not using this, so I could not test. Could you prepare a full-fledged pull-request? (But please remove unnecessary parentheses in return).

Note that `EntryStream` has separate `nonNullKeys()` and `nonNullValues()`

**Comment by nathanila** [comment]
I got StreamEx compiling and packaging on my machine.  Instead of trying to figure out all of the various issues, I ripped out of the pom.xml those parts that weren't working.

I wrote the following test code in another project.  This test code flagged an error on the assignment to dest.

```
      try
      (
         StreamEx<@Nullable Object> source = StreamEx.of((Object) null);
         StreamEx<@NonNull Object>  dest   = source.nonNull();
      )
      {
         dest.forEach(System.out::println);
      }
```

I then added the following method to StreamEx.java and built the Jar.

```
   @Override
   public StreamEx<T> nonNull() {
      return super.nonNull();
   }
```

I then added the External Annotation in the other project and the compiler error went away.  Thus, I have shown that adding nonNull() to StreamEx.java will be sufficient.  Can you add this to StreamEx?

**Comment by amaembo** [comment]
Ok, hopefully this is enough.
