### ISSUE TITLE
Add reverseSortedBy

### ISSUE THREAD

**Issue by aeding** [amaembo/streamex#134]
It would be nice to have reverseSortedBy in addition to sortedBy.

**Comment by amaembo** [comment]
No, I think it's too much and will result in API bloat. Anyways it's impossible to cover all cases (one may want to sort by several fields, etc.). Use comparator combinators like `.reverseSorted(Comparator.comparing(keyExtractor))`.

**Comment by aeding** [comment]
Sure, that is what I am doing today. However, I think this is a fairly common use-case (at least as common as sortedBy which already exists today) and it would be nice to have symmetry here.

**Comment by amaembo** [comment]
For symmetry I should add not only `reverseSortedBy`, but also `reverseSortedByInt`, `reverseSortedByLong`,  `reverseSortedByDouble` in four classes separately (`AbstractStreamEx`, `IntStreamEx`, `LongStreamEx`, `DoubleStreamEx`), which is 16 methods. Thus I'd stay with single level of shortcuts here.

See:

- sorted() - no shortcut
- sortedBy(key) = sorted(comparing(key)) - cutting one call
- sortedByInt(key) = sorted(comparingInt(key)) - cutting one call
- sortedByLong(key) = sorted(comparingLong(key)) - cutting one call
- sortedByDouble(key) = sorted(comparingDouble(key)) - cutting one call
- reverseSorted() = sorted(reverseOrder()) - cutting one call

- reverseSortedBy(key) = sorted(comparing(key, reverseOrder())) - cutting two calls

If I start cutting two calls, other people would ask for more shortcuts cutting two calls, e.g.
- sortedByNullsFirst(key) = sorted(nullsFirst(comparing(key)))
or
- sortedBy(key1, key2) = sorted(comparing(key1).thenComparing(key2))
There are much more combinations of two calls, so it would blow up the API completely. Thus I'd like to limit library to cut one call only.
