### ISSUE TITLE
Add StreamEx#toNavigableMap

### ISSUE THREAD

**Issue by JeanFrancoisSavard** [amaembo/streamex#137]
It is great to have a method such as toSortedMap, but many times when you want a SortedMap you want to navigate over it easily and this can be achieved easily with a NavigableMap hence having a method toNavigableMap would be helpful.

I'll provide some code later if the interests is there.

**Comment by amaembo** [comment]
The code is not necessary as this is pretty trivial (actually `toSortedMap` always creates a navigable map currently). That was my mistake to create `toSortedMap` instead of `toNavigableMap`. I will add it as well.
