### ISSUE TITLE
Null as key in groupingBy

### ISSUE THREAD

**Issue by viartemev** [amaembo/streamex#138]
Please, add ability for grouping by null in streams.
Current implementation of Java 8 streams doesn't support it, and I don't know why, because
 implementation use HashMap:
`return groupingBy(classifier, HashMap::new, downstream);`
But HashMap can store null keys.

**Comment by amaembo** [comment]
I don't like doing this as my `groupingBy` may switch automatically to `ConcurrentHashMap` for unordered parallel collection, which does not tolerate null keys. Allowing them in one case and disabling in another would be confusing.

**Comment by viartemev** [comment]
@amaembo thanks a lot for explain
