### ISSUE TITLE
DropWhile but keep previous item

### ISSUE THREAD

**Issue by wafisher** [amaembo/streamex#139]
Say I have input data `[1, 2, 3, 4, 5]` representing times and I'd like to keep all the times in the future _and_ the time right before now. For example, if `t = 3.5`, the output should be `[3, 4, 5]`. Right now, I'm reverse sorting, using `takeWhileInclusive()` and re-sorting in order to accomplish this.

Is there a good, idiomatic way to do this with the current library APIs?

**Comment by amaembo** [comment]
Well assuming the input is presorted I can suggest the following solution which does not involve sorting:

```java
double fence = 3.5;

LongStreamEx.of(1,2,3,4,5)
            .append(Long.MAX_VALUE)
            .pairMap((a, b) -> b > fence ? a : Long.MIN_VALUE)
            .without(Long.MIN_VALUE)
            .forEach(System.out::println);
```

So we form pairs like (1, 2), (2, 3), (3, 4), (4, 5) and (5, Long.MAX_VALUE), then return the left value if the right one is bigger than supplied fence and finally exclude Long.MIN_VALUE values.

Note that for presorted data it would be much more efficient to use binary search instead of streams.

**Comment by wafisher** [comment]
Thank you for the thorough answer. On a more conceptual level, do you think this is good code? I've been using StreamEx extensively but every now and then will come across an example like this and find myself desperately wanting to write my solution in StreamEx but feeling like I'm jamming a square peg into a round hole.

Your code does accomplish the given task, but it doesn't strike me as very readable. _I_ certainly wouldn't be able to guess the purpose here without a good comment. Which leads to the following: should streams be used for something like this?

It seems there are three possible answers:

1. Yes, and the above clearly demonstrates how one would use streams. (I don't buy this one but you may.)
2. Yes, and there should be a call in StreamEx that makes something like this easier/clearer. Predicates over a window perhaps? Indexes? I'm honestly not sure.
3. No, if the current StreamEx API set doesn't cover this, it's probably best written imperatively.

Would love your input on the matter!

**Comment by amaembo** [comment]
This is of course not clear to have such things inside business logic, but nobody stops you from encapsulating it:

```java
// in some utility class
public static UnaryOperator<LongStreamEx> dropWhileButTakePrevious(double fence) {
    return s -> s.append(Long.MAX_VALUE)
                 .pairMap((a, b) -> b > fence ? a : Long.MIN_VALUE)
                 .without(Long.MIN_VALUE);
}

// usage:
public static void main(String[] args) {
    LongStreamEx.of(1,2,3,4,5).chain(dropWhileButTakePrevious(3.5)).forEach(System.out::println);
}
```

I honestly believe that you should do something like `Arrays.binarySearch()` or `Collections.binarySearch()`, then use `Arrays.copyOfRange` or `List.subList`. This is just way more efficient than linear search. If you actually need a stream afterwards, you can use `Arrays.stream(longArray, foundIndex, longArray.length)` or `myList.subList(foundIndex, myList.size()).stream()`.

**Comment by wafisher** [comment]
Makes sense. Sounds like I should just do things imperatively: find the index using another method (`binarySearch()`) and slice the list myself. Feel free to close.
