### ISSUE TITLE
StreamEx.split() as reverse operation of EntryStream.join()

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#140]
EntryStream.join() returns a StreamEx<String> by taking the key and value and concatenating them (with a delimiter).  I would like to do the reverse operation.  I have a StreamEx<String> and I would like to split each String into 2 pieces based on a delimiter and have a EntryStream<String, String>.  If the delimiter is not found, then the key will have the entire String and the value will have an empty String.  Can you add such a method?  Or is there an already easy solution?

**Comment by amaembo** [comment]
The name "split" is already taken to create a stream source. Also there are many tiny details like what should we do if the delimiter appears several times. Probably some people would like to drop strings without delimiter or throw an exception. Currently I don't see how make this more universal...

Currently available solution is not very long:

`stream.map(str -> str.split(delimiter, 2)).mapToEntry(arr -> arr[0], arr -> arr.length > 1 ? arr[1] : "")`

Thus I'm not sure whether more specific solution is necessary...

**Comment by amaembo** [comment]
A possible simplification is to use a `chain()` method. Add the following method into your utility class:

```java
    static Function<StreamEx<String>, EntryStream<String, String>> split(String delimiter) {
        return s -> s.map(str -> str.split(delimiter, 2)).mapToEntry(arr -> arr[0], arr -> arr.length > 1 ? arr[1] : "");
    }
```

Then you may use it like this:

```java
Map<String, String> map = StreamEx.of("a=b", "c=d", "foo", "bar=", "baz=qux").chain(split("=")).toMap();
```

This way you have strict type control (it can be applied to `StreamEx<String>` only) and you may encode all the quirks you want. Want to skip malformed strings like `foo` (without '=')? Just add `filter(arr -> arr.length == 2)`. Want to consider strings having several '=' as invalid? No problem, change `str.split(delimiter, 2)` to `str.split(delimiter)`. All such modifications are very easy to write manually in your project, but quite hard to encode in the API to fulfill the needs of every user.
