### ISSUE TITLE
add flatArray() shortcut

### ISSUE THREAD

**Issue by mmariotti** [amaembo/streamex#141]
Hello, 
sometimes I need to flatMap an array, that can possibly be null.
This scenario is not so common, but it is encountered. 
A trivial (but meaningful) example is when working with Files, because `File.listFiles()` states:
> If this abstract pathname does not denote a directory, then this method returns null. Otherwise an array of File objects is returned, one for each file or directory in the directory.

So, to flat file structure (single level) you have to:

```
// specific approach: null-check is based on doc statement
.flatMap(x -> x.isDirectory() ? Arrays.stream(x.listFiles()) : null)
```
OR
```
// specific approach: same as before, but using only method references
.filter(File::isDirectory) 
.map(File::listFiles)
.flatMap(Arrays::stream)
```
OR
```
// generic approach: preemptive null pruning (sub-optimal time consuming?)
.map(File::listFiles) 
.nonNull()
.flatMap(Arrays::stream)
```

Because of this, I suggest to add the `AbstractStreamEx.flatArray` just like the  `AbstractStreamEx.flatCollection`:
```
public <R> StreamEx<R> flatArray(Function<? super T, ? extends R[]> mapper) {
	return flatMap(t -> {
		R[] a = mapper.apply(t);
		return a == null ? null : Arrays.stream(a);
	});
}
```

Thank you!

**Comment by amaembo** [comment]
Thank you for your suggestion. I don't remember why I did not added it before. I though that there was some problem with generics or something. Nevertheless seems that it works.

Also used `StreamEx.of(Arrays.spliterator(a))` and `StreamEx.of(c.spliterator())`. This is actually more efficient for many short streams than standard JDK stream.

**Comment by mmariotti** [comment]
Thank you! I owe you a couple of beers ;)
