### ISSUE TITLE
Stream parallelism doesn't work when using takeWhile

### ISSUE THREAD

**Issue by johanhaleby** [amaembo/streamex#142]
I have a stream that I create like this:

```java
StreamEx.generate(new MySupplier<List<Entity>>())
		.flatMap(List::stream)
		.map(Entity::getName)
               .map(name -> ...)
               .. // more stuff
```

I can change this to work in parallel by just adding `parallel`:

```java
StreamEx.generate(new MySupplier<List<Entity>>())
		.flatMap(List::stream)
		.map(Entity::getName)
               .map(name -> ...)
               .parallel()
               .. // more stuff
```

But I also want to add a `takeWhile` condition to make the stream stop:

```java
StreamEx.generate(new MySupplier<List<Entity>>())
                .takeWhile(not(List::isEmpty))
		.flatMap(List::stream)
		.map(Entity::getName)
               .map(name -> ...)
               .parallel()
               .. // more stuff
```

But as soon as I add the `takeWhile` the stream becomes sequential. According to the javadoc of `takeWhile`, if I understand it correctly, should work with parallel streams. Am I doing something wrong or is this according to design?

**Comment by amaembo** [comment]
Fixed for unordered streams, thanks.

**Comment by johanhaleby** [comment]
Many thanks for your help and support!
