### ISSUE TITLE
EntryStream.generate()

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#144]
Consider adding to EntryStream a method with the following signature:

`public static <K, V> EntryStream<K, V> generate(Supplier<K> keys, Supplier<V> values);`

Each time a new entry is needed, this will call `keys` and `values` 1 time each to make the entry.

I suppose an alternative solution is:

```
StreamEx.
   generate(keys).
   mapToEntry(key -> values.get());
```

**Comment by amaembo** [comment]
Looks not very difficult. Do you have real problem which requires such feature?

**Comment by nathanila** [comment]
Yes, I have a real problem which prompted this feature request.  However, I don't know if it is needed.  The alternative solution works fine.  So, unless there is some sort of performance or usability angle, I am not sure if EntryStream.generate() is needed.

**Comment by amaembo** [comment]
Implemented.
