### ISSUE TITLE
intersperse()

### ISSUE THREAD

**Issue by orionll** [amaembo/streamex#145]
I would like to propose an intermediate operation that takes a value and "intersperses" that value between the values of the stream. Example:

```java
StreamEx.of("Line1", "Line2", "Line3").intersperse("----").forEach(System.out::println);
```
This will print:
```
Line1
----
Line2
----
Line3
```

I know there is already a `joining` method but it requires memory for storing the whole String. If the stream is very large (e.g. lines of a big text file) this can fail with OutOfMemoryError.

**Comment by lukaseder** [comment]
A simple workaround is this:

```java
stream.flatMap(s -> Stream.of("----", s)).skip(1);
```

**Comment by amaembo** [comment]
Wow, @lukaseder, you're so fast!

**Comment by orionll** [comment]
I think this is a satisfactory solution. I actually already thought about `flatMap`, but I had the reverse order of arguments in `Stream.of()`. That would require a `skipLast` method.

**Comment by amaembo** [comment]
FYI, `skipLast` can be emulated via `pairMap((a, b) -> a)`

**Comment by lukaseder** [comment]
@amaembo: I've implemented it before ;)

**Comment by amaembo** [comment]
It was actually in my backlog for a very log time, but I was reluctant to implement it given limited demand and easy workaround.
