### ISSUE TITLE
EntryStream flatMap to EntryStream with key and value

### ISSUE THREAD

**Issue by Lexanius** [amaembo/streamex#154]
Hi,

is it possible to `flatMapKeyValue `a `EntrySteam/Stream<Entry<...>>` in a `EntryStream `and return a `EntryStream` without creating new Object ?

Example:
`EntryStream.of(map).flatMapKeyValue((key, value) -> functionThatProduceEntryStream(key, value));`

I can call now `EntryStream.of(blub)` but this creates a new Stream around. is there a better way?

Thanks for the answer

**Comment by amaembo** [comment]
You can use `EntryStream.of(map).flatMapKeyValue(...).chain(EntryStream::of)`. This will not add another level of indirection. `EntryStream.of()` detects if `EntryStream` or `StreamEx<Entry>` object is supplied and unwraps it (see the [implementation](https://github.com/amaembo/streamex/blob/59d5cee1e364c76ff258684899897da7213d520f/src/main/java/one/util/streamex/EntryStream.java#L1533)). So, the original wrapper (which is quite tiny object) gets garbage collected. You add a single additional allocation, but it's not the thing you should worry when using Stream API.
