### ISSUE TITLE
add `distinct(Function<? super Appointment, ?> keyExtractor,long atLeast)` method

### ISSUE THREAD

**Issue by anjia0532** [amaembo/streamex#160]
```
class A {
    string id,
    string key
}
StreamEx.of(new A().id("1").key("1"),new A().id("2").key("1")).distinct(A::key,2) ==> [A{id="1",key="1"}]

```

now
```
Map map = StreamEx.of(new A().id("1").key("1"),new A().id("2").key("1"))
    .groupingBy(A::key);
map.values().removeIf(a -> a.size <2);
System.out.println(map);
```

**Comment by amaembo** [comment]
What you want is a grouping intermediate operation (with subsequent filter on groups). Unlike existing `distinct()` and even `distinct(atLeast)` this operation would require intermediate buffering of the whole stream content. Moreover, it cannot start any downstream operation until it's finished. So in practice it's more like a terminal operation. I don't like to add operations which look like an intermediate, but behave like a terminal (except sorting operations which are part of original Stream API). It's not a big problem to make this in two steps, but it will be much more clear that intermediate buffering is required, so your operation takes a significant amount of memory.
