### ISSUE TITLE
EntryStream.of(V[]) for primitive arrays

### ISSUE THREAD

**Issue by shmosel** [amaembo/streamex#163]
Disclaimer: I'm not a user of this library (yet). But I was wondering if there's a way to stream the indices and values of a primitive `int` array as an `EntryStream<Integer, Integer>`, and it doesn't seem to be possible currently. Is that accurate? Would it make sense to add primitive overloads? Or how about a more generic method to convert any `StreamEx<T>` to `EntryStream<Integer, T>` using indices?

**Comment by amaembo** [comment]
I'm reluctant to add many methods which do implicit boxing, but some of them exist, so your problem could be solved in two steps:

```java
static EntryStream<Integer, Integer> ofIntArray(int[] array) {
    return IntStreamEx.ofIndices(array).mapToEntry(idx -> idx, idx -> array[idx]);
}
```

You can add such method to your utility class and use it if you often need such operation.

To add indices to any existing stream you can use this method:

```java
static <T> EntryStream<Integer, T> zipWithIndices(Stream<T> stream) {
    return IntStreamEx.ints().boxed().zipWith(stream);
}
```

Some people find it more convenient to create a function instead:

```java
static <T> Function<Stream<T>, EntryStream<Integer, T>> zipWithIndices() {
    return stream -> IntStreamEx.ints().boxed().zipWith(stream);
}
```

This way you can utilize `chain` method:

```java
StreamEx.of("foo", "bar", "baz").chain(zipWithIndices());
```
