### ISSUE TITLE
google guava support/scope of project  ?

### ISSUE THREAD

**Issue by loordgek** [amaembo/streamex#165]
what is the scope of this project? are you going to support other libs ?
can you look into support 

multiMap
https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/Multimap.java

table
https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/Table.java

RangeMap
https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/RangeMap.java

**Comment by amaembo** [comment]
No, StreamEx is not intended to have any external dependencies, thus any interop with Guava is out of the scope. I believe, Guava has its own collectors.
