### ISSUE TITLE
StreamEx.filterBy(Function<T, K>, Predicate<K>)

### ISSUE THREAD

**Issue by orionll** [amaembo/streamex#175]
```java
StreamEx.of(customers).filterBy(Customer::getCity, "novosibirsk"::equalsIgnoreCase);
```
What do you think?

**Comment by amaembo** [comment]
`StreamEx.of(customers).filterBy(Customer::getCity, "novosibirsk"::equalsIgnoreCase);`

Not better than 

`StreamEx.of(customers).filter(c -> "novosibirsk".equalsIgnoreCase(c.getCity()));`

Method reference composing is a way to nowhere. Tomorrow you will want `filterBy(BiPredicate, secondParameterForPredicate)` or something else. Use lambdas or create you own utility methods to decompose to method references if you really want (like `filter(by(Customer::getCity, "novosibirsk"::equalsIgnoreCase))`) for some `public static Function by(Function, Predicate)` method in utility class.

**Comment by orionll** [comment]
What's the point of the current filterBy then?

`StreamEx.of(customers).filterBy(Customer::getCity, "Novosibirsk");`

not better than

`StreamEx.of(customers).filter(c -> Objects.equals(c.getCity(), "Novosibirsk");`

**Comment by amaembo** [comment]
You always have to draw line somewhere between "rich" and "bloated" API. Remember that I have not only `filter`, but also `remove`, `filterKeys`, `filterValues`, `removeKeys` and `removeValues`. Also `findFirst(filter)` is a shortcut to `filter().findFirst()` and one might want to update `anyMatch` in the same way. You ask for one method, but I will need to add dozens of them.
