### ISSUE TITLE
@SuppressWarnings("OptionalUsedAsFieldOrParameterType")

### ISSUE THREAD

**Issue by PongPong** [amaembo/streamex#177]
In StreamEx.java, should add the annotation to suppress the code inspection warning.

    @SuppressWarnings("OptionalUsedAsFieldOrParameterType")
    public static <T> StreamEx<T> of(Optional<? extends T> optional) {
        return optional.isPresent() ? of(optional.get()) : empty();
    }

**Comment by amaembo** [comment]
Hello!

Please use the committed [inspection profile](https://github.com/amaembo/streamex/blob/master/.idea/inspectionProfiles/Project_Default.xml) where this inspection is disabled. I prefer to move such settings to profile when possible, instead of polluting the source code.
