### ISSUE TITLE
Should StreamEx#parallel accept ExecutorService instead of ForkJoinPool?

### ISSUE THREAD

**Issue by JeanFrancoisSavard** [amaembo/streamex#181]
I understand that the default implementation of Stream's use a ForkJoinPool, which I believe is the reason why StreamEx enforce this type.

Am I correct? Else, could the parallel accept a ExecutorService?

**Comment by amaembo** [comment]
This would not work. Internally parallel stream executes task in current FJP if any or in common pool. It cannot execute in custom ExecutorService, so adding this feature would mean complete reimplementation of stream parallelization which is out of scope of StreamEx.
