### ISSUE TITLE
EntryStream.toMap(), toCustomMap() and into() blocks null values

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#186]
EntryStream.toMap(), toCustomMap() and into() will throw a NullPointerException if a null value is put into the Map.  This is clearly by design since the code calls Objects.requireNonNull().  What is the reason for the decision?

Because of this design decision, the following code does not work.

```
HashMap<Object, Object> source, dest;

source = new HashMap<>();

source.put(null, null);

EntryStream.
   of(source).
   toMap();
```

So, instead this code must be written which requires allocating a lambda and possibly taking a performance hit.

```
EntryStream.
   of(source).
   forKeyValue(dest::put);
```

**Comment by amaembo** [comment]
Duplicates #149.
