### ISSUE TITLE
SonarCloud

### ISSUE THREAD

**Issue by bannmann** [amaembo/streamex#187]
In addition to (or instead of) Coveralls, StreamEx should use [SonarCloud](https://sonarcloud.io), the cloud offering of SonarQube. It's free for open source projects, offers nearly 500 static code analysis rules for Java and includes coverage analysis and various metrics.

**Comment by amaembo** [comment]
I don't see why I should. Which benefits exactly would I get from Sonar integration? As you can see, I already have coverage. Next, I use very powerful static analyzer which is built in into IntelliJ IDEA. And metrics are mostly useful to please management with fancy charts which hardly correlate with real product state. I have no management here, so there's nobody to please with metrics.

Finally people say that LGTM and Codacy are much better alternatives.
