### ISSUE TITLE
Provide stream -> streamEx map mutator

### ISSUE THREAD

**Issue by Gaibhne** [amaembo/streamex#190]
Because I am working in a huge project, I can't control all parts of it, and a lot of times, I am passed a stream the creation of which I can't control, such as:

    protected void doStuff(Stream<OurDomainElement> elements) { ... }

it would be nice if I could turn that stream into a StreamEx stream, like so:

    protected void doStuff(Stream<OurDomainElement> elements) { 
        List<OurDomainElement> sanitizedElements = elements.map(StreamEx::fromStream).nonNull().toList();
    }

I imagine this should be comparatively easy to implement, but I'm not familiar enough with the internals of streams to dare a PR.

**Comment by amaembo** [comment]
Use `StreamEx.of(elements).nonNull().toList()`.

**Comment by Gaibhne** [comment]
My apologies, I could have sworn that overload wasn't there when I specifically checked StreamEx.of prior to posting this :man_facepalming:
