### ISSUE TITLE
Provide interop `.stream()` method

### ISSUE THREAD

**Issue by binkley** [amaembo/streamex#195]
Several popular Java libraries take Streams as arguments, and unfortunately assume the exact type is `Stream` rather than `? extends Stream`.  I'm looking at AssertJ, where substituting a Stream with a StreamEx does not compile:
```
assertThat(returnsStreamEx(...)).someAssertions();
```
The problem is this signature in AssertJ:
```
<ELEMENT> ListAssert<ELEMENT> assertThat(Stream<? extends ELEMENT> actual)
```
To get it compiling, I wrote a shim function, but this makes a lot of mess combined with static import of `assertThat`:
```
<T, S extends Stream<? extends T>> ListAssert<T> assertThat(S actual)
```
It would help for StreamEx to have an interoperability method to upcast a `StreamEx` back to a `Stream` for cases like this.  Perhaps something like:
```
assertThat(returnsStreamEx(...).asJdkStream()).someAssertions();
```

**Comment by amaembo** [comment]
Hello! I don't think this is necessary. I think it's a really rare case when you need to assert something about the StreamEx object itself. Often it's sufficient to add `.toList()` call and assert something about the list content. Also to resolve overload ambiguity you can add an explicit cast: `assertThat((Stream<?>)returnsStreamEx(...))`. This is not longer than calling a proposed `asJdkStream()` method. Adding such a method would pollute an API and confuse users.
