### ISSUE TITLE
Auto-closing finite streams

### ISSUE THREAD

**Issue by oleg-smith** [amaembo/streamex#196]
@amaembo Does it make sense to add a flag that will automatically call `onClose()` on a stream, if the end of the stream is reached?

**Comment by amaembo** [comment]
I don't think so. This would increase internal complexity which may affect the performance and memory footprint for 99% of cases when closing is unnecessary. Also I want StreamEx to be fully compatible with Stream, so everywhere where Stream is accepted StreamEx could be used without behavior change.

**Comment by oleg-smith** [comment]
Ok, and is there a technical capability to catch such end-of-stream condition safely, with a guarantee it is safe to call close handlers?

**Comment by amaembo** [comment]
Technically it's possible to override every terminal operation except `iterator()` and `spliterator()` and call some handler there in `finally` after the main processing is finished (carefully composing the exceptions, of course). On the other hand some library code might use `iterator()` and `spliterator()`. Good example:

```java
StreamEx.ofLines(path1).map(String::trim)
  .anyMatch(predicate); // we may intercept anyMatch() and call close() after that
StreamEx.ofLines(path2).map(String::trim)
  .anyMatch(predicate); // so far so good
Stream.concat(StreamEx.ofLines(path1), StreamEx.ofLines(path2)).map(String::trim)
  .anyMatch(predicate); // oops
```

`Stream.concat` internally aquires spliterators of source streams, then creates a new stream which traverses these spliterators. In case of short-circuiting terminal operation `anyMatch` spliterators are just abandoned when the match is found. If we close the resulting stream explicitly, it will close the underlying streams as well, but we cannot do this automatically anymore. So this feature would be fragile.

**Comment by oleg-smith** [comment]
But aggregating stream remembers what streams it was created from, and just close all of them even in case of a short-circuit operation?

**Comment by lihy70** [comment]
@oleg-smith [AbacusUtil](https://github.com/landawn/AbacusUtil) provides the auto-closed streams. For example: `Stream.lines(file).count();` the stream will be closed after one of terminal operations is executed. (except one scenario, as @amaembo mentioned: `stream.iterator()`)

**Comment by stefanrybacki** [comment]
Terminal operations should call close on the underlying stream. This will also work on concat since concat know the incoming streams and can close them when its wrapper stream is closed.
