### ISSUE TITLE
Type-safe version of StreamEx.select?

### ISSUE THREAD

**Issue by hpple** [amaembo/streamex#199]
Hello, Tagir.

What do you think about adding type-safe version of **select** method?

Something like:
```
public <TT extends T> StreamEx<TT> selectStrictly(Class<TT> clazz) {...}
```

Literally, the same it was in the old revision before [#28](https://github.com/amaembo/streamex/issues/28), but as a separate method.

Rationale is to prevent cases when you may accidentally forget to perform map to desired type before using select and end up with empty stream without any clue about it.

**Comment by amaembo** [comment]
I doubt people would actually use a new method with a longer name just to add some type safety... Probably it would be better to make a separate unsafe method with a longer name, but what's done is done. Now, this would look more like API pollution...
