### ISSUE TITLE
Shouldn't empty collector return emptyList()?

### ISSUE THREAD

**Issue by Miha-x64** [amaembo/streamex#211]
https://github.com/amaembo/streamex/blob/d60b3497813958878f2a521747405c2f6b2a2536/src/main/java/one/util/streamex/MoreCollectors.java#L85
Why not
```java
 return empty(Collections::emptyList); 
```
?

**Comment by amaembo** [comment]
No. You are looking at a private method that is used from a number of collectors (e.g. `head(0)`) that normally returns a mutable list, so it would be confusing to see sometimes mutable, sometimes immutable list.
