### ISSUE TITLE
Add to readme all extra feature provided by streamex.

### ISSUE THREAD

**Issue by foal** [amaembo/streamex#22]
For example, I will need to "merge" two streams. Look to  https://github.com/amaembo/streamex - nothing :(

So I found out the operation name on Google ("zip"), in parallel I found several other libraries provide such functionality (protonpack, Lazy-Seq) and only after it in Eclipse I realized that such method is exists in StreamEx.

**Comment by foal** [comment]
The SO question that may be updated with StreamEx :)

http://stackoverflow.com/questions/17640754/zipping-streams-using-jdk8-with-lambda-java-util-stream-streams-zip

**Comment by amaembo** [comment]
Actually StreamEx cannot merge (zip) two *streams*. Such operation cannot be implemented efficiently for parallel streams, so I decided not to make this at all. So I cannot answer to that SO question. Instead you can "merge" two arrays or random access lists via [`StreamEx.zip`](http://amaembo.github.io/streamex/javadoc/javax/util/streamex/StreamEx.html#zip-java.util.List-java.util.List-java.util.function.BiFunction-) or [`EntryStream.zip`](http://amaembo.github.io/streamex/javadoc/javax/util/streamex/EntryStream.html#zip-java.util.List-java.util.List-). I wrote, for example, [this](http://stackoverflow.com/a/30271289/4856258) and [this](http://stackoverflow.com/a/32345142/4856258) answers to describe such feature.

Currently the primary information source for StreamEx is [JavaDoc](http://amaembo.github.io/streamex/javadoc/). It's quite comprehend and describes almost all methods (though some are still missing the documentation). Adding every single feature to the README.md sounds too much. However I'm thinking about writing the tutorial describing most of the features with some real world examples. Unfortunately so far I had no time to work on such tutorial. If you want to write it by yourself, pull requests are welcome :-)

**Comment by foal** [comment]
For readme IMHO perfectly enough just a mention of an extra functionality. For instance, "limited zip operation support" is Ok :)

**Comment by amaembo** [comment]
Ok, I'll think about it. Thank you for suggestion.

**Comment by amaembo** [comment]
I committed a [Cheatsheet](https://github.com/amaembo/streamex/blob/master/CHEATSHEET.md) which lists currently all the additional methods of `StreamEx/EntryStream/IntStreamEx/LongStreamEx/DoubleStreamEx` classes (new collectors are yet to be added). Please take a look. Is it something you're looking for?

**Comment by foal** [comment]
Yes! It is much more than I asked. Learned a lot :)

One note - for the following updates it will be better to add one more column with a version - since such feature appeared.

**Comment by amaembo** [comment]
Ok, as you're satisfied, I'm closing this issue :-)

I don't like adding version number to the cheatsheet. Version numbers are already present in JavaDoc. Adding them to cheatsheet would make it overcrowded. If you want to see the latest changes, just check [CHANGES.md](https://github.com/amaembo/streamex/blob/master/CHANGES.md). In general if you use the latest version you always have all the available features and there's no need to know when such feature appeared first.

**Comment by amaembo** [comment]
By the way are you the author of [org.jresearch.logui](http://search.maven.org/#artifactdetails|org.jresearch.logui|org.jresearch.logui.backend|1.0.1|jar)? I reviewed the usage of StreamEx in this code (seems that it's the first artifact published in Maven Central which depends on StreamEx!) and has a couple of simple advices. If you want, you may contact me via e-mail (lany@ngs.ru) for details.
