### ISSUE TITLE
Simplify distinct operator if follows the sorted operator

### ISSUE THREAD

**Issue by numeralnathan** [amaembo/streamex#227]
Let's say we have the following stream pattern...

    ...
    sorted().
    distinct().
    ...

The distinct operator can be simplified.  Instead of putting all of the elements into a `Set`, the distinct operator only needs to compare to the previous element.

This will reduce the memory usage from O(n) to O(1).

**Comment by amaembo** [comment]
I believe, it's already done in JDK, and we delegate to JDK streams. See https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/stream/DistinctOps.java#L124
