### ISSUE TITLE
Feature request: flatMapToEntry(), but with mapper type to Stream instead of Map

### ISSUE THREAD

**Issue by jasper-smit** [amaembo/streamex#231]
I want to do something like this
````java
StreamEx.of(...)
.flatMapToEntry(element -> { .... })
.groupingTo(ArrayList::new)
}
````
However, because the mapper of  `flatMapToEntry` has to deliver a `Map` i can only produce unique keys.

**Comment by amaembo** [comment]
Sorry, I don't understand. Can you provide an example input and the desired output?

Probably the `cross()` method will suit your needs?

**Comment by jasper-smit** [comment]
Yes, `cross()` looks indeed what i needed. Thanks for pointing me in the right direction.
