### ISSUE TITLE
Opposite analog of filter(Predicate) with invert logic

### ISSUE THREAD

**Issue by Ksnz** [amaembo/streamex#235]
There are a lot of cases where i have to use `!` mark in filter method.
E.g. `.filter(campaignId -> !lastActualizedDates.getOrDefault(campaignId, LocalDate.MIN).isAfter(period.getTo()))` 
or write a lot of verbose code to avoid that.

It would be nice to have a method like `skipWhen(Predicate)` or `skipIf(Predicate)`  or  just `skip(Predicate)`  to write more safe and less brain-breaking or verbose code.

**Comment by amaembo** [comment]
There's a `remove` method that behaves exactly opposite to `filter`. Well probably the name is not very ideal.
