### ISSUE TITLE
Add IntStreamEx.toSet()

### ISSUE THREAD

**Issue by numeralnathan** [amaembo/streamex#241]
IntStreamEx already has toBitSet().  This only works if the integers are non-negative and not too large.  I have a stream of integers that can range from -1 to 31.  Please add Set<Integer> toSet() method to handle this case.

**Comment by amaembo** [comment]
Hello! You can easily do `.boxed().toSet()`. I don't want to add a shortcut here, because it should be explicit that numbers will be boxed in this case.
