### ISSUE TITLE
multi-release-jar file link broken in maven repository after version 0.7.0

### ISSUE THREAD

**Issue by ayinger1** [amaembo/streamex#245]
ivy resolver fails to find multi-release-jar file:

 [NOT FOUND  ] one.util#streamex;0.7.3!streamex.multi-release-jar
==== central: tried
  https://repo1.maven.org/maven2/one/util/streamex/0.7.3/streamex-0.7.3.multi-release-jar

the link to the multi release jar file is broken on mvnrepository.com:
  https://mvnrepository.com/artifact/one.util/streamex/0.7.3
-> https://repo1.maven.org/maven2/one/util/streamex/0.7.3/streamex-0.7.3.multi-release-jar

the other, non-multi-release jar files are present, however, as can be seen here:
  https://repo1.maven.org/maven2/one/util/streamex/0.7.3/

**Comment by amaembo** [comment]
Even though it's a multi-release jar, the artifact type is just 'jar', not 'multi-release-jar'. I don't see any problem here. Why would you need to find multi-release-jar artifact?

**Comment by amaembo** [comment]
Note that mvnrepository is a third-party service I have no connection to. If they have a bug, please report the problem to the service owner.

**Comment by ayinger1** [comment]
well it if it's a bug, it affects ivy and mvnrepository both.  that is, they both attempt to retrieve the multi-release-jar by default (which, i agree with you, is not what we want here.)

i can get it to retrieve the the jar artifact if i explicitly define a child artifact type, like:

<dependency org="one.util" name="streamex" rev="0.7.3"  conf="*->default" >
   		<artifact name="streamex" type="jar" />

but then the eclipse Ivy.DE plugin fails to auto-retrieve the source/javadocs (so, here is a third instance where third-party tools can't handle multi-release-jar default).

**Comment by amaembo** [comment]
Probably something should be changed here indeed... Thanks. Will try to dig into this when having more time.

**Comment by amaembo** [comment]
It should be better now

**Comment by amaembo** [comment]
@ayinger1 please check whether version 0.8.1 works fine for you. Thanks.
