### ISSUE TITLE
Fix building with JDK 16

### ISSUE THREAD

**Issue by Thihup** [amaembo/streamex#247]
In JDK 13, the option `--no-module-directories` was removed from Javadoc, so building with a current JDK, fails the build with 
`Exit code: 1 - javadoc: error - invalid flag: --no-module-directories`.

More info: https://bugs.openjdk.java.net/browse/JDK-8215582

**Comment by amaembo** [comment]
I updated pom.xml to avoid this option and tested that it's possible to build using Java 17. Still, reference builds are created using Java 11.
