### ISSUE TITLE
Implement negated filter method

### ISSUE THREAD

**Issue by Su5eD** [amaembo/streamex#257]
The `Stream#filter` method is commonly used with a negated operation, which requires using the negation operator `!` and prevents shortening code with method references. I propose the introduction of `Stream#filterNot` to eliminate this issue. 

A simple implementation and use case may be as follows:
```java
// one.util.streamex.AbstractStreamEx

public S filterNot(Predicate<? super T> predicate) {
    return filter(predicate.negate());
}
```

```java
public static void givenDays_returnWeekDays() {
    List<String> days = Arrays.asList("mon", "tue", "wed", "thu", "fri", "sat", "sun");
    List<String> weekend = Arrays.asList("sat", "sun");
    
    List<String> weekdays = StreamEx.of(days).filterNot(weekend::contains).toList(); 
}
```

**Comment by Suicolen** [comment]
Such function already exists in `AbstractStreamEx` and it's called `remove` instead
