### ISSUE TITLE
Ability to map Float[] to float[]

### ISSUE THREAD

**Issue by cowwoc** [amaembo/streamex#258]
Feature request: Ability to map from `Float[]` to `float[]` without casting to double along the way.

**Comment by cowwoc** [comment]
The closest I could find is:

`DoubleStreamEx.of(Arrays.stream(boxedFloatArray).mapToDouble(Float::doubleValue)).toFloatArray();`

1. It's not clear whether this casts to double along the way.
2. The API could be cleaner.

Ideally I'd want to invoke `DoubleStreamEx.of(boxedFloatArray).toFloatArray()` and/or consider adding `FloatStreamEx`.

**Comment by amaembo** [comment]
You can do this simpler:
```java
float[] floats = StreamEx.of(boxedFloatArray).mapToDouble(x -> x).toFloatArray();
```

Given that `float` type is not so popular, and there's rarely the necessity to create a `Float[]` array, I don't think that merging `StreamEx.of(boxedFloatArray).mapToDouble(x -> x)` into a single call would be really useful for many people. Note that you can always create a utility method like this in your project:

```java
public class StreamUtils {
  public static DoubleStream of(Float[] floats) {
    return StreamEx.of(boxedFloatArray).mapToDouble(x -> x);
  }
}
```

**Comment by cowwoc** [comment]
@amaembo `float` is extremely popular in the machine-learning world. As far as I'm aware, `double` is never used.

For what it's worth, I ended up making my own functions:

```
	/**
	 * Unboxes an array of floats.
	 *
	 * @param array an array of boxed types
	 * @return an array of primitive types
	 * @throws NullPointerException if {@code array} is null
	 */
	public static float[] unbox(Float[] array)
	{
		float[] result = new float[array.length];
		for (int i = 0; i < result.length; ++i)
			result[i] = array[i];
		return result;
	}

	/**
	 * Boxes an array of floats.
	 *
	 * @param array an array of boxed types
	 * @return an array of primitive types
	 * @throws NullPointerException if {@code array} is null
	 */
	public static Float[] box(float[] array)
	{
		Float[] result = new Float[array.length];
		for (int i = 0; i < result.length; ++i)
			result[i] = array[i];
		return result;
	}
```

It is simple enough, and does not ever cast to `double`.

**Comment by amaembo** [comment]
Sure, these transformations are simple enough to write once with loops. This also would be faster and produce less garbage, compared to streams.
