### ISSUE TITLE
Pom: License url is not replaced with property

### ISSUE THREAD

**Issue by hfhbd** [amaembo/streamex#265]
https://repo1.maven.org/maven2/one/util/streamex/0.8.1/streamex-0.8.1.pom

```
<licenses>
  <license>
    <name>Apache License, Version 2.0</name>
    <url>${license.url}</url>
    <distribution>repo</distribution>
  </license>
</licenses>
```

**Comment by amaembo** [comment]
It looks like it should not. If you create an effective pom out of this file with `mvn help:effective-pom`, it will be replaced properly. It's perfectly normal to use properties in the pom, and I believe they should not be replaced in Maven repository, as Maven tool will automatically replace them when reading.
