### ISSUE TITLE
mapMulti

### ISSUE THREAD

**Issue by mmariotti** [amaembo/streamex#269]
Hello Tagir,

![image](https://github.com/amaembo/streamex/assets/7235289/0cdd3f36-fce5-44b8-b7dd-2029501d066e)

As you can see, the `.toSet()` gives a compilation error, because StreamEx does not override `Stream#mapMulti` which is a default method.

Is it possible to override to return a StreamEx instead of a normal Stream?
If it's not possible (maybe for compatibility), is it possible to workaround it?

Thanks!

**Comment by amaembo** [comment]
Hello!

I'll try to do this for object stream. Unfortunately, it's hard to do this for primitive streams (`IntStreamEx`, etc.), as their `mapMulti` methods refer to the new functional interface, which is not available in previous Java versions.
