### ISSUE TITLE
Provide factory method zip(List<K> keys, V constant) in EntryStream

### ISSUE THREAD

**Issue by mizhoux** [amaembo/streamex#271]
Currently, if we want to zip keys with a single value to get an `EntryStream`, we need to do this:

```java
void demo(List<Long> userIds, Config config) {
    // EntryStream<Long, Config>
    StreamEx.of(userIds).zipWith(StreamEx.constant(config, userIds.size()));
}
```

If `EntryStream` had a factory method like this:

```java
public static <K, V> EntryStream<K, V> zip(List<K> keys, V constant) {
    // Maybe we can implement it more efficiently than:
    // StreamEx.of(keys).zipWith(StreamEx.constant(constant, keys.size()))
}
```

Then it's much easier (and efficient) to use:

```java
void demo(List<Long> userIds, Config config) {
    // EntryStream<Long, Config>
    EntryStream.zip(userIds, config);
}
```

**Comment by amaembo** [comment]
Hello!

In this case, you don't need `zip`. It's better to use [`mapToEntry`](https://javadoc.io/doc/one.util/streamex/latest/one.util.streamex/one/util/streamex/StreamEx.html)

```java
StreamEx.of(userIds).mapToEntry(() -> config)
```

This is essentially not a zipping, it's a plain mapping of a single element to a pair.

**Comment by mizhoux** [comment]
Wow, thanks for helping me find the method.
