### ISSUE TITLE
method collapseKeys on unsorted EntryStream

### ISSUE THREAD

**Issue by wangguofeng1923** [amaembo/streamex#276]
Map<String,List<Integer>> map1= EntryStream.of("1", 1,"2",4, "1", 2).sortedBy(Entry::getKey).collapseKeys().toMap();//works fine
System.out.println(map1);  // {1=[1, 2], 2=[4]}

//Duplicate entry for key '1' (attempt to merge values '[1]' and '[2]')
Map<String,List<Integer>> map2= EntryStream.of("1", 1,"2",4, "1", 2).collapseKeys().toMap();
System.out.println(map2); 

**not sure this is feature or bug. thx**

**Comment by amaembo** [comment]
Yes, it's expected. As [javadoc](https://www.javadoc.io/doc/one.util/streamex/latest/one.util.streamex/one/util/streamex/EntryStream.html#collapseKeys()) says, collapse "Merge series of _adjacent_ stream entries with equal keys". 

The easiest way to solve your problem is to use `grouping()`:

```java
Map<String, List<Integer>> map = 
            EntryStream.of("1", 1, "2", 4, "1", 2).grouping();
```
