### ISSUE TITLE
Poor `StreamEx.ofLines` parallel performance

### ISSUE THREAD

**Issue by almson** [amaembo/streamex#3]
`BufferedReader`'s spliterator (taken from `Spliterators.spliteratorUnknownSize` which returns an `IteratorSpliterator`) has very large granularity (1024 lines minimum), which makes it impractical for many tasks. See this thread: http://stackoverflow.com/questions/22569040/readerlines-parallelizes-badly-due-to-nonconfigurable-batch-size-policy-in-it

I propose that `StreamEx` implements its own spliterator. There's a number of ways to do it. I think the most flexible would be to read ahead a certain number of bytes (eg, 256KB). If the file is smaller than that then we can know how many lines it has and return a real (ie, known-size) spliterator. If the file is larger than that, then we return something similar to an `IteratorSpliterator`, but I think it should still have a much smaller granularity than 1k.

I wrote in the comments to my harshly down-voted answer that the root problem is the spliterator. It's meant to work well when the data is in memory (and is either in a randomly-accessible collection or a tree). It works poorly when we're, you know, actually *STREAMING* data. The irony. What are your thoughts on that?

**Comment by amaembo** [comment]
I will think about this, but it's not a first priority for now. I never tried using parallel streams with I/O in practice, but I think that there are not so many tasks where such change will be useful. If you have small file with CPU-consuming per-line processing, then reading it to the `List` sequentially, then process in parallel would be much better. You will not keep the file open during the whole operation, so you free the file handler faster (there are limited number of them usually) and file gets unlocked faster on Windows. If you have really big file, so reading it into memory seems to be unreasonable, then current spliterator strategy should work well. Anyways if we propose a new strategy, then it will be at least no worse than existing one for the most of common usages, thus extensive testing would be necessary.

**Comment by amaembo** [comment]
I committed an optimized general purpose [IteratorSpliterator](https://github.com/amaembo/streamex/commit/16e1c2ecfc5d214c1feea6b953ccfbeb505ea273) for iterators of unknown size. Some benchmarking results are here:

    (parallel) (impl)  (n)       Score     Error  Units
         true  base      3       4.973 ±   0.142  us/op
         true  base     10       9.882 ±   0.128  us/op
         true  base     30      18.633 ±   1.027  us/op
         true  base    100      46.394 ±   1.753  us/op
         true  base    300     163.285 ±   5.719  us/op
         true  base   1000     496.049 ±   5.257  us/op
         true  base   3000    1944.159 ±  40.606  us/op
         true  base  10000    6916.634 ± 116.902  us/op
         true  jdk       3       3.499 ±   0.162  us/op
         true  jdk      10       8.191 ±   0.184  us/op
         true  jdk      30      23.898 ±   0.543  us/op
         true  jdk     100      79.470 ±   1.810  us/op
         true  jdk     300     295.881 ±  15.301  us/op
         true  jdk    1000     817.950 ±  11.145  us/op
         true  jdk    3000    2954.316 ± 120.163  us/op
         true  jdk   10000    7970.635 ± 175.836  us/op
         true  opt       3       2.768 ±   0.105  us/op
         true  opt      10       7.877 ±   0.131  us/op
         true  opt      30      15.094 ±   2.210  us/op
         true  opt     100      47.337 ±   1.638  us/op
         true  opt     300     187.816 ±   8.407  us/op
         true  opt    1000     577.947 ±  12.567  us/op
         true  opt    3000    2317.630 ±  31.987  us/op
         true  opt   10000    7497.548 ± 170.823  us/op
        false  base      3       1.807 ±   0.015  us/op
        false  base     10       5.540 ±   0.025  us/op
        false  base     30      18.449 ±   0.497  us/op
        false  base    100      62.752 ±   1.968  us/op
        false  base    300     273.997 ±  17.264  us/op
        false  base   1000     876.322 ±  53.642  us/op
        false  base   3000    3633.522 ± 301.100  us/op
        false  base  10000   13811.535 ± 394.655  us/op
        false  jdk       3       2.208 ±   0.066  us/op
        false  jdk      10       6.519 ±   0.500  us/op
        false  jdk      30      22.797 ±   0.815  us/op
        false  jdk     100      71.748 ±   4.562  us/op
        false  jdk     300     310.781 ±   1.379  us/op
        false  jdk    1000     813.416 ±  24.592  us/op
        false  jdk    3000    3082.675 ±  44.448  us/op
        false  jdk   10000   11969.098 ± 946.530  us/op
        false  opt       3       2.197 ±   0.043  us/op
        false  opt      10       6.223 ±   0.421  us/op
        false  opt      30      21.203 ±   1.403  us/op
        false  opt     100      70.029 ±   3.649  us/op
        false  opt     300     283.029 ±  22.234  us/op
        false  opt    1000     928.026 ±  51.289  us/op
        false  opt    3000    3741.137 ± 190.673  us/op
        false  opt   10000   13142.609 ± 224.455  us/op

This is `map(...).collect(Collectors.toList())` with quite CPU-consuming `map` operation. The `base` is `ArrayList.spliterator` which is very fast and should parallelize ideally. The `jdk` is `Spliterators.spliteratorUnknownSize` and `opt` is my new implementation. As you can see, for parallel streams my implementation is consistently better especially when the stream size (n) is approaching to `1024`. The problem I fixed is the transition from iterator mode to array mode. JDK spliterator splits badly at this point: it returns the `ArraySpliterator` while the original spliterator remains of zero size. This results in uneven tasks distribution. My spliterator supports both array mode and iterator mode and during the transition it changes itself as well.

More testing (and probably some minor optimization) is necessary, but for now results look quite promising. Meanwhile you can checkout the [optimized-iterator](https://github.com/amaembo/streamex/tree/optimized-iterator) branch and test it by yourself.

**Comment by amaembo** [comment]
One more benchmark on different PC (previous was Core Duo, this one is Core Quad):

    (parallel)  (task) Bench   (n)     Score     Error  Units
          true    trim base      3     4.388 ±   0.074  us/op
          true    trim base     10     4.758 ±   0.063  us/op
          true    trim base     30     5.563 ±   0.061  us/op
          true    trim base    100     6.397 ±   0.069  us/op
          true    trim base    300     8.483 ±   0.165  us/op
          true    trim base   1000    15.197 ±   0.167  us/op
          true    trim base   3000    36.790 ±   0.433  us/op
          true    trim base  10000   113.301 ±   0.453  us/op
          true    trim opt       3     3.074 ±   0.638  us/op
          true    trim opt      10     4.581 ±   0.253  us/op
          true    trim opt      30     5.187 ±   0.280  us/op
          true    trim opt     100     6.221 ±   0.116  us/op
          true    trim opt     300     8.939 ±   0.095  us/op
          true    trim opt    1000    19.280 ±   0.207  us/op
          true    trim opt    3000    39.390 ±   0.374  us/op
          true    trim opt   10000   139.564 ±   0.763  us/op
          true    trim jdk       3     0.949 ±   0.048  us/op
          true    trim jdk      10     1.120 ±   0.038  us/op
          true    trim jdk      30     1.708 ±   0.015  us/op
          true    trim jdk     100     3.827 ±   0.027  us/op
          true    trim jdk     300     9.622 ±   0.186  us/op
          true    trim jdk    1000    28.922 ±   0.188  us/op
          true    trim jdk    3000    62.417 ±   1.589  us/op
          true    trim jdk   10000   158.365 ±   1.704  us/op
          true pattern base      3     3.437 ±   0.031  us/op
          true pattern base     10     6.062 ±   0.147  us/op
          true pattern base     30     8.841 ±   0.101  us/op
          true pattern base    100    18.512 ±   0.300  us/op
          true pattern base    300    61.321 ±   1.734  us/op
          true pattern base   1000   183.992 ±   2.254  us/op
          true pattern base   3000   713.093 ±  12.119  us/op
          true pattern base  10000  2640.950 ± 158.411  us/op
          true pattern opt       3     1.840 ±   0.019  us/op
          true pattern opt      10     5.547 ±   0.070  us/op
          true pattern opt      30     8.968 ±   0.156  us/op
          true pattern opt     100    29.080 ±   0.447  us/op
          true pattern opt     300   114.732 ±   1.296  us/op
          true pattern opt    1000   337.576 ±   2.276  us/op
          true pattern opt    3000  1028.520 ±  59.679  us/op
          true pattern opt   10000  3500.588 ± 172.535  us/op
          true pattern jdk       3     2.445 ±   0.104  us/op
          true pattern jdk      10     5.476 ±   0.078  us/op
          true pattern jdk      30    15.863 ±   0.240  us/op
          true pattern jdk     100    52.176 ±   0.280  us/op
          true pattern jdk     300   205.931 ±   0.881  us/op
          true pattern jdk    1000   650.993 ±   6.407  us/op
          true pattern jdk    3000  2008.242 ± 119.288  us/op
          true pattern jdk   10000  3729.162 ±  77.707  us/op
         false    trim base      3     0.160 ±   0.001  us/op
         false    trim base     10     0.362 ±   0.003  us/op
         false    trim base     30     1.029 ±   0.007  us/op
         false    trim base    100     2.684 ±   0.015  us/op
         false    trim base    300     7.741 ±   0.040  us/op
         false    trim base   1000    25.161 ±   0.138  us/op
         false    trim base   3000    74.723 ±   0.598  us/op
         false    trim base  10000   251.570 ±   2.004  us/op
         false    trim opt       3     0.162 ±   0.005  us/op
         false    trim opt      10     0.370 ±   0.001  us/op
         false    trim opt      30     1.048 ±   0.011  us/op
         false    trim opt     100     2.784 ±   0.013  us/op
         false    trim opt     300     8.062 ±   0.059  us/op
         false    trim opt    1000    26.731 ±   0.314  us/op
         false    trim opt    3000    81.857 ±   3.357  us/op
         false    trim opt   10000   268.170 ±   1.764  us/op
         false    trim jdk       3     0.169 ±   0.001  us/op
         false    trim jdk      10     0.369 ±   0.011  us/op
         false    trim jdk      30     1.043 ±   0.010  us/op
         false    trim jdk     100     2.904 ±   0.011  us/op
         false    trim jdk     300     8.330 ±   0.027  us/op
         false    trim jdk    1000    27.141 ±   0.130  us/op
         false    trim jdk    3000    82.460 ±   2.825  us/op
         false    trim jdk   10000   262.285 ±   2.556  us/op
         false pattern base      3     1.526 ±   0.016  us/op
         false pattern base     10     4.874 ±   0.064  us/op
         false pattern base     30    14.952 ±   0.190  us/op
         false pattern base    100    50.237 ±   0.154  us/op
         false pattern base    300   202.622 ±   1.001  us/op
         false pattern base   1000   651.412 ±   8.618  us/op
         false pattern base   3000  2549.271 ±  44.269  us/op
         false pattern base  10000  9604.081 ± 677.764  us/op
         false pattern opt       3     1.488 ±   0.015  us/op
         false pattern opt      10     4.828 ±   0.028  us/op
         false pattern opt      30    14.933 ±   0.100  us/op
         false pattern opt     100    50.249 ±   0.206  us/op
         false pattern opt     300   205.956 ±   2.160  us/op
         false pattern opt    1000   645.647 ±   8.016  us/op
         false pattern opt    3000  2503.915 ±  36.142  us/op
         false pattern opt   10000 10338.934 ± 677.660  us/op
         false pattern jdk       3     1.486 ±   0.009  us/op
         false pattern jdk      10     4.837 ±   0.039  us/op
         false pattern jdk      30    14.782 ±   0.123  us/op
         false pattern jdk     100    50.223 ±   0.208  us/op
         false pattern jdk     300   203.604 ±   1.046  us/op
         false pattern jdk    1000   653.912 ±   2.627  us/op
         false pattern jdk    3000  2685.241 ± 164.101  us/op
         false pattern jdk   10000  9995.800 ± 899.325  us/op

The `trim` task is `map(String::trim)` and `pattern` task is the complex regexp replacement. On parallel tests for `trim` task JDK spliterator wins on `n <= 100`, because here less parallelism is actually better. Results of `opt` version are close to `base` (`ArrayList.spliterator`). I guess this can be ignored as sequential version for such task sizes is much faster.

The disappointing thing is that while `opt` version almost 2x faster than `jdk` on parallel pattern test, it's still almost 2x slower than `base` for `n=300..1000`.

**Comment by amaembo** [comment]
We had some [discussion](http://mail.openjdk.java.net/pipermail/core-libs-dev/2015-July/034528.html) about this issue in core-libs-dev mailing list. Note that `Files.lines` in JDK 9 is already optimized for regular files shorter than 2Gb, now it's really parallel-friendly.

**Comment by amaembo** [comment]
I finally found a better solution to this problem. Now all the processors should be used when `ofLines` is executed and parallel performance should reach the maximum. On the other hand the general batching strategy did not change (it still starts with 1024 lines). Some minor overhead could be added when processing very long files ( > 1000000 lines ) compared to JDK implementation, but preliminary benchmarks show that it's negligible. If JDK-9 optimized Files.lines is available (when using `StreamEx.ofLines(path)`), then it will be used instead of my optimization. The code is committed and targeted to 0.5.2 release. You may test it if you want.
