### ISSUE TITLE
Add short-circuiting reducingWithZero() collector

### ISSUE THREAD

**Issue by amaembo** [amaembo/streamex#39]
It's possible to add a short-circuiting reducing collectors like this:

```
public static <T> Collector<T, ?, Optional<T>> reducingWithZero(T zero, BinaryOperator<T> op);
public static <T> Collector<T, ?, T> reducingWithZero(T zero, T identity, BinaryOperator<T> op);
```

Here `zero` is the element which satisfies the following property: for any `t` `op.apply(zero, t)` is equal to `op.apply(t, zero)` and equal to `zero`. So when `zero` is reached, further reduction could be stopped.

Also, a shortcut StreamEx.reduceWithZero == collect(reducingWithZero) should be created

Examples:

```
StreamEx.of(integers).reduceWithZero(0, 1, (a, b) -> a*b));
StreamEx.of(integers).reduceWithZero(Integer.MAX_VALUE, Math::max));
StreamEx.of(integers).reduceWithZero(0, (a, b) -> a & b)); // like andingInt()
StreamEx.of(integers).reduceWithZero(0xFFFFFFFF, (a, b) -> a | b));
StreamEx.of(sets).reduceWithZero(Collections.emptySet(), 
  (set1, set2) -> StreamEx.of(set1).filter(set2::contains).toSet())); // like intersecting()
```
- [x] Implementation
- [x] Tests
- [ ] JavaDoc
- [ ] Changes
- [ ] Cheatsheet

**Comment by nbardiuk** [comment]
Hi @amaembo,
I also had a need for short-circuiting reduction like `foldLeft` with condition to continue
```java
StreamEx.of(integers).foldLeft(0, (a, b) -> a + b, s -> s < 100)

<S, T> S foldLeft(S identity, BiFunction<S,T,S> mapper, Predicate<S> predicate)
```
After some tinkering I've found that it can be implemented using other primitives like
```java
StreamEx.of(integers).scanLeft(0, (a, b) -> a + b).takeWhile(s -> s < 100).collect(last())
```
It would work nice if `scanLeft` returns `Stream` instead of `List`. 

Such `scanLeft` can be implemented as a `quasi-intermediate` operator. And it could probably compensate some use-cases you have in examples and even give more flexible API how to terminate reduction
```java
StreamEx.of(integers).scanLeft(1, (a, b) -> a*b).takeWhileInclusive(m -> m !=0).collect(last());
StreamEx.of(integers).scanLeft(Math::max).takeWhileInclusive(m -> m != Integer.MAX_VALUE).collect(last());
StreamEx.of(integers).scanLeft((a, b) -> a & b).takeWhileInclusive(r -> r != 0).collect(last());
StreamEx.of(integers).scanLeft((a, b) -> a | b).takeWhileInclusive(r -> r != 0xFFFFFFFF).collect(last());
StreamEx.of(sets).scanLeft((set1, set2) -> StreamEx.of(set1).filter(set2::contains).toSet())
    .takeWhileInclusive(s -> !s.isEmpty()).collect(last());
```

**Comment by amaembo** [comment]
This is somewhat different from the original bugreport: `foldLeft` cannot parallelize independently.

It's not very hard to implement such `scanLeft` using the `headTail` operation. See [this example](https://github.com/amaembo/streamex/blob/7734dc5c9e63d85fc1ea9d54f7dfcd88c121904f/src/test/java/one/util/streamex/StreamExHeadTailTest.java#L205).

~~~~java
private static <T> StreamEx<T> scanLeft(StreamEx<T> input, BinaryOperator<T> operator) {
    return input.headTail((head, tail) -> scanLeft(tail.mapFirst(cur -> operator.apply(head, cur)), operator)
                .prepend(head));
}
    
static <T> UnaryOperator<StreamEx<T>> scanLeft(BinaryOperator<T> operator) {
    return stream -> scanLeft(stream, operator);
}

StreamEx.of(integers).chain(scanLeft((a, b) -> a+b)).takeWhile(s -> s < 100).collect(last());
~~~~

Actually I was thinking about integration of such scenarios directly into the library. The usual concern is that such `scanLeft` intermediate operation is badly parallelized. I usually avoid badly parallelizable intermediate operations especially if they could be expressed via `headTail` (which is one of a few badly parallelizable operations I like: it allows to implement almost everything else).

**Comment by danieldietrich** [comment]
> it allows to implement almost everything else

Yep, namely inherently recursive (= Foldable) data structures. I like it how Erik Meyer explains it in his course [FP101x](https://www.edx.org/course/introduction-functional-programming-delftx-fp101x-0)

**Comment by nbardiuk** [comment]
Great to learn about `headTail` - very useful recursion primitive

**Comment by amaembo** [comment]
@nbardiuk I finally decided to make dedicated operation for quasi-intermediate `scanLeft()` -- see issue #94.
