### ISSUE TITLE
Flat mapping of collection with optional

### ISSUE THREAD

**Issue by foal** [amaembo/streamex#49]
Hi, 

Take a look on http://short-coding-notes.blogspot.cz/2014/09/flatten-list-of-optional-values-in-java.html

Is it implemented somehow in streamex? 

Best,
Stas

**Comment by amaembo** [comment]
Hello!

You can do this using `StreamEx.of(Optional)`:

    collection.stream() // or StreamEx.of(collection) - doesn't matter in this example
        .map(this::someMethodThatReturnsAnOptional)
        .flatMap(StreamEx::of)
        .collect(...)

Or in single flatMap statement:

    collection.stream() // or StreamEx.of(collection) - doesn't matter in this example
        .flatMap(val -> StreamEx.of(someMethodThatReturnsAnOptional(val)))
        .collect(...)

Probably adding `flatMapToOptional` to `StreamEx` class is possible as it will simplify this even further:

    StreamEx.of(collection)
        .flatMapToOptional(this::someMethodThatReturnsAnOptional)

But I doubt it's worthy. What if your method returns `OptionalInt`, `OptionalLong` or `OptionalDouble`? Should we add also `.flatMapToOptionalInt` and friends? Should we add all these methods to primitive streams (like `IntStreamEx`)? In total we will have 20 new methods: `(EntryStream, StreamEx, IntStreamEx, LongStreamEx, DoubleStreamEx) × (flatMapToOptional, flatMapToOptionalInt, flatMapToOptionalLong, flatMapToOptionalDouble)`. So I'm hesitating to do this now, taking into account that currently available alternative is not much longer. Currently you can use `.flatMapToInt(val -> IntStreamEx.of(methodReturningOptionalInt(val)))`, so all these 20 methods are covered by not very long alternatives.

**Comment by foal** [comment]
Thank you the `.map(this::someMethodThatReturnsAnOptional).flatMap(StreamEx::of)` is Ok for me with only one "but" - it will wrap/unwrap to StreamEx each element in a collection. It may be a performance issue for big collections (not a my case).

**Comment by amaembo** [comment]
Ok, closing as won't fix for now. If the performance issue would become critical, comment here providing the profiling/benchmarking results.

By the way there's issue #10 which proposes adding the `chain()` method to make streams easier to extend. Assuming the #10 is implemented you can create your own static method:

	public static <T, R> Function<StreamEx<T>, StreamEx<R>> flatMapOptional(
			Function<? super T, Optional<? extends R>> mapper) {
		return stream -> stream.map(mapper).filter(Optional::isPresent).map(Optional::get);
	}

And use it like this:

    StreamEx.of(collection)
        .chain(flatMapOptional(this::someMethodThatReturnsAnOptional))
        .toList();

This way you don't have an additional overhead for intermediate Stream creation. Probably I should raise the priority of `chain()` feature. It could be quite useful...

**Comment by amaembo** [comment]
By the way after applying #57 optimization the `.flatMap(StreamEx::of)` works much faster as it does not actually create JDK stream at all. For empty optional it allocates `StreamEx` only (using predefined empty spliterator), for non-empty optional it allocates `StreamEx` and simple spliterator for one element. Sometimes we can skip JDK Stream creation and the `StreamEx` itself is much more light-weight than `Stream`.

I tested this benchmark:

    @Benchmark
    public void flatOptional(Blackhole bh) {
      IntStreamEx.range(10000).mapToObj(Optional::of).map(op -> op.filter(x -> x % 2 == 0))
                      .flatMap(StreamEx::of).forEach(bh::consume);
    }

The resulting time (in microseconds) is the following for StreamEx 0.5.3 and upcoming 0.5.4:

test | 0.5.3 | 0.5.4
---|---:|---:
flatOptional | 420,880 | 240,456
