### ISSUE TITLE
JavaDoc

### ISSUE THREAD

**Issue by Sirikid** [amaembo/streamex#5]
Почему бы не написать
```java
/** {@inheritDoc} */
```
перед каждым методом из Stream?

**Comment by amaembo** [comment]
Подскажите, как сконфигурировать maven, чтобы это сработало. Он же должен знать, где взять исходники JDK, чтобы в скомпилированный JavaDoc вставить текст документации из JDK. Я что-то не сообразил как это сделать без привязки к абсолютным путям в системе.

Там ещё в нетерминальных операциях уточняется возвращаемый тип, так что исходная документация может не точно соответствовать оригиналу. В терминальных было бы полезно, наверно.

**Comment by Sirikid** [comment]
Maven не пользуюсь, разберусь - пришлю пул реквест

**Comment by amaembo** [comment]
Если удастся подобрать нужный набор опций javadoc, тоже напишите. Мне почему-то даже этого не удалось. В maven я уж как-нибудь интегрирую.

**Comment by Sirikid** [comment]
А задачка оказалась не из легких

**Comment by Sirikid** [comment]
Методами гугления, тостерения и научного тыка выяснил что javadoc не таскает доки из zip-архивов, но и не ругается на них.

**Comment by amaembo** [comment]
По идее можно взять этот src.zip, распаковать из него только пакет java.util.stream в какую-нибудь временную папку и добавить её в sourcepath к javadoc. Но тогда возвращаемся к вопросу, как это сделать по-человечески с помощью maven. В принципе путь к src.zip можно указать через какой-нибудь ${java.home}, но я не очень представляю, каким плагином организовать распаковку.

**Comment by amaembo** [comment]
Сделал экспериментальную ветку [stream-javadoc](https://github.com/amaembo/streamex/tree/stream-javadoc). В ней добавил распаковку пакета java/util/stream из src.zip с помощью плагина antrun и добавил распакованное в пути к JavaDoc. Вроде что-то получается. Только пришлось выключить doclint, потому что в JDK используются всякие теги типа @implspec, которые не поддерживаются официально. Ещё проблема — проект теперь выдаёт ошибку в Eclipse, потому что у него нет байндинга для плагина antrun. Мне хочется, чтобы в эклипсе всё работало. Возможно, стоит поискать альтернативный способ раззиповать кусок src.zip. Ещё не работают ссылки на всякие terminal operation и т. д. Они обычно выглядят как 

    <a href="package-summary.html#StreamOps">terminal operation</a>

В принципе можно в пакете streamex тоже сделать кратенькое описание типов операций… У меня как раз свой новый тип добавлен — quasi-intermediate.

Можете посмотреть, у вас работает? Сделайте какой-нибудь `mvn package` и посмотрите, как документация сгенерируется.

**Comment by amaembo** [comment]
В целом жизнь налаживается. Eclipse удалось легко уговорить, кратенькое описание добавил в package-summary для используемых понятий, удалил дублирующую документацию. Жалко только, что doclint пришлось отключить, он казался полезным. И нестыковки с типами кое-где вылезли, как я и ожидал. Например, в `StreamEx.mapToInt`:

> Returns an `IntStream` consisting ...

А на самом деле возвращает `IntStreamEx`. Но на это пока можно закрыть глаза. Ещё потестирую немного и, видимо, волью в master-ветку.

**Comment by amaembo** [comment]
doclint [удалось вернуть](https://github.com/amaembo/streamex/commit/86e6609fc2fac92d09c3680248777700d847ea20) — просто делаю отдельный проход javadoc без JDK-исходников с doclint и результаты игнорирую. Попробовал собрать с другой машины — вроде нормально. Может, конечно, какой-нибудь maven-гуру скажет, что так жить нельзя, но по крайней мере работает.

**Comment by Sirikid** [comment]
Intellij IDEA, встроенный плаги Maven - полет нормальный

**Comment by amaembo** [comment]
Влил ветку в master. Будет в версии 0.3.3
