### ISSUE TITLE
EntryStream.sortKeys() and EntryStream.sortValues()

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#62]
Please consider adding the following methods to `EntryStream`.

> public EntryStream<K, V> sortKeys()
> {
>    return(sortKeys(Comparator.naturalOrder()));
> }
> 
> public EntryStream<K, V> sortValues()
> {
>    return(sortValues(Comparator.naturalOrder()));
> }
> 
> public EntryStream<K, V> sortKeys(Comparator<K> comparator);
> public EntryStream<K, V> sortValues(Comparator<V> comparator);

This may or may not be useful.  The workaround for `sortKeys()` is `sortedBy(Map.Entry::getKey)` which isn't terribly difficult.  However, I don't know if this means a Map.Entry() has to be allocated with each element of the stream or perhaps for the entire stream.

**Comment by amaembo** [comment]
Currently the proper way to do this is `.sorted(Map.Entry.comparingByKey())` and `.sorted(Map.Entry.comparingByValue())`. Though `sortedBy(Map.Entry::getKey)` could also be used. Also `.sortValues(Comparator)` can be expressed as `.sorted(Map.Entry.comparingByValue(Comparator))` (you may use `import static java.util.Map.Entry.*` to shorten this further). 

The problem with proposed no-args `sortKeys()` and `sortValues()` is that they assume keys or values to be `Comparable`. This cannot be checked in compile time and may result in `ClassCastException` at runtime. The same problem with existing `sorted()` method, but it's standard API. Adding new methods which don't have compile-time type checking seems not very good... Currently existing alternatives have proper type checking.

**Comment by nathanila** [comment]
I forgot about compiler enforcing of Comparable.  It seems that the current APIs are the best we can do.
