### ISSUE TITLE
Stream groupBy() values

### ISSUE THREAD

**Issue by rednoah** [amaembo/streamex#65]
Is there a non-terminal version of `groupBy` or some other neat way to stream through the resulting Map entries/values?

I find myself wanting to stream through the values after `groupBy` but the best I could come up with is not pretty:
```
StreamEx.ofValues(StreamEx.of(0, 1, 2, 4).groupingBy(i -> i % 2)).mapToInt(ii -> IntStreamEx.of(ii).sum())
// RESULT: [6, 1]
```

**Comment by amaembo** [comment]
The correct way to do this is to use downstream collector:

    Collection<Integer> result = StreamEx.of(0, 1, 2, 4)
            .groupingBy(i -> i % 2, Collectors.summingInt(i -> i)).values();

This is more readable as your solution and more efficient (as you don't collect intermediate lists, but sum elements directly).

**Comment by rednoah** [comment]
Is there something like `summingInt` but for merging streams or collections instead of ints?

**Comment by amaembo** [comment]
Please provide full example input and expected output.

**Comment by rednoah** [comment]
We have sequences of numbers that we want to group together. However we only want to group number sequences that are in the same category A, B or C.

I wonder if there's a way to simplify this by nifty use of Collectors:
```
List<Entry<Character, List<Integer>>> ss = new ArrayList<>();
ss.add(new AbstractMap.SimpleEntry<>('A', Arrays.asList(1, 2, 3)));
ss.add(new AbstractMap.SimpleEntry<>('B', Arrays.asList(0, 6, 7)));
ss.add(new AbstractMap.SimpleEntry<>('C', Arrays.asList(8, 9, 0)));
ss.add(new AbstractMap.SimpleEntry<>('A', Arrays.asList(4, 5, 6)));

List<List<Integer>> list = StreamEx.ofValues(StreamEx.of(ss).groupingBy(e -> e.getKey())).flatMap((group) -> {
	return StreamEx.of(group).flatCollection(e -> e.getValue()).groupRuns((a, b) -> a + 1 == b);
}).toList();

// OUTPUT: [[1, 2, 3, 4, 5, 6], [0], [6, 7, 8, 9], [0]]
System.out.println(list);
```

**Comment by amaembo** [comment]
I see. Quite unusual data transformation. In this case I would recomment to introduce an intermediate variable to explicitly show that the intermediate result is collected:

    Map<Character, List<Entry<Character, List<Integer>>>> map = StreamEx.of(ss)
                 .groupingBy(e -> e.getKey());
    List<List<Integer>> list = StreamEx.ofValues(map)
            .flatMap(
                    (group) -> StreamEx.of(group).flatCollection(e -> e.getValue())
                                .groupRuns((a, b) -> a + 1 == b)
                    ).toList();

As stream is lazy, it's not very good idea to hide the fact that everything is collected into the intermediate collection. Here you explicitly show that `map` is created, so it's evident that additional memory is necessary. Also this way it's easier to debug as you have intermediate variable.

A slightly modified way to write the same which I would prefer (just a matter of taste):

    Map<Character, List<Integer>> map = EntryStream.of(ss.stream())
            .flatMapValues(List::stream).grouping();
    List<List<Integer>> list = StreamEx.ofValues(map)
            .flatMap(group -> StreamEx.of(group).groupRuns((a, b) -> a + 1 == b)).toList();
