### ISSUE TITLE
limitSort()

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#69]
Please consider adding a method called limitSort(long max, ...) with all of the flavors sorted().  This method will return a stream which has up to max elements.  Passing Long.MAX_VALUE to max causes the limitSort() to behave the same as sorted().  Passing a lower value of max causes the "highest" elements to be discarded.

For example, if I need to look at the 10 oldest files, then I could do something like...

StreamEx<File> stream;

stream.
   limitSort(10, File::lastModified).
   ...

One could implement the same logic with the following...

stream.
   sorted(File::lastModified).
   limit(10).
   ...

However, this pattern will hold all of the File objects in memory and sort them.  Ouch!  Whereas, limitSort() only needs to hold up to 10 (in this case) File objects in memory.

Instead of implementing limitSort(), StreamEx could see a sorted() followed by a limit() and then merge the two operators into 1.

**Comment by amaembo** [comment]
This was already discussed [here](https://github.com/amaembo/streamex/issues/61#issuecomment-175963625). This operation would act as full-barrier and I don't like adding full-barrier intermediate operations especially given the fact that we already have a collector which does the same (`MoreCollectors.least()`). You should instead collect the intermediate result to the list and start a new stream from it (if you actually want to continue streaming). Hiding the fact that everything is actually buffered during the intermediate operation is not very good (normal `sorted()` is a notable exception, it's part of original API and too important). That's why terminal operations and collectors exist: to show you that you have a hard-copy of your data.

If you nevertheless want to have this as intermediate operation, there's always `chain` and `headTail` at your service:

    public static <T> UnaryOperator<StreamEx<T>> limitSorted(Comparator<T> comparator, int n) {
        @SuppressWarnings("unchecked")
        Collector<T, Object, List<T>> collector = (Collector<T, Object, List<T>>) MoreCollectors.least(comparator, n);
        return stream -> collectAndStream(stream, collector.supplier().get(), collector.accumulator(), collector
                .finisher().andThen(StreamEx::of));
    }
    
    private static <T, A, R> StreamEx<R> collectAndStream(StreamEx<T> input, A buf, BiConsumer<A, T> accumulator, Function<A, StreamEx<R>> finisher) {
        return input.headTail((head, tail) -> {
            accumulator.accept(buf, head);
            return collectAndStream(tail, buf, accumulator, finisher);
        }, () -> finisher.apply(buf));
    }

Use it like this:

    stream.chain(limitSorted(Comparator.comparing(File::lastModified), 10))...

So to conclude I must reject this proposal. Instead you may write these 12 lines of code in some utility class and use them.

Finally note that if some files were modified during the pipeline execution, you might get random results as comparator might have symmetry and transitivity violated.

**Comment by nathanila** [comment]
Instead of implementing limitSort(), StreamEx could see a sorted() followed by a limit() and then merge the two operators into 1.  Maybe StreamEx wants to get into optimizing the stream.  Maybe StreamEx wants to leave such optimizations to the programmer.

**Comment by amaembo** [comment]
It's somewhat problematic. First, I claim that my library is 100% compatible with existing Stream API. Which means that if I upcast `StreamEx` object to `Stream` and pass it to some code which is not aware about my library, then it should behave in the same manner and with similar performance. Replacing standard operation with custom implementation makes the operation quasi-intermediate which has subtle differences compared to normal intermediate operation. In particular, adding `.parallel()` after quasi-intermediate operation may not parallelize the Stream (or parallelize only partially). So the behavior will change which is bad.

Another problem is that current implementation of `MoreCollectors.least()` relies on `PriorityQueue` which is 1) does not support nulls 2) produces unstable result. So blindly using the current `MoreCollectors.least()` implementation in `sorted().limit()` chain would break the existing code which wants to sort nulls (with custom comparator) and wants to see the stable result. It's possible to implement custom `PriorityQueue` which is free of these disadvantages. But there's another problem: when the input is already sorted (or almost sorted) in the reverse order compared to current order (which is quite possible), then `PriorityQueue`-based selection becomes really slow as every element should be shifted down to the end of priority queue. I did quick benchmarks. Random numbers

    new Random(1).ints(1_000_000).boxed().sorted().limit(1000).toArray();

JDK: 531ms, my implementation: 18ms - cool!

Presorted in forward direction:

    IntStream.range(0, 1_000_000).boxed().sorted().limit(1000).toArray();

JDK: 42ms, my implementation: 8.9ms - not so cool, but probably ok.

Presorted in reverse direction:

    IntStream.range(0, 1_000_000).mapToObj(i -> ~i).sorted().limit(1000).toArray();

JDK: 42ms, my implementation: 177ms - awful.

Degrading the performance of such common case is inacceptable.

**Comment by nathanila** [comment]
I agree that optimizing sorted() and limit() via merging the operators should only be done if the performance is better.  Since the reverse direction hurts performance, then sorted/limited combined operator would need more work.  Theoretically, O(n log n) > O(n log k) where n > k.  However, plain sorted() is using a highly optimized sort algorithm.  So, sorted/limited combined operator would need to start there.

In a QuickSort, if the pivot falls higher than the limit, then everything after the pivot can be thrown out.  The downside of this is that the entire data set has to be kept in memory until the first pass.  Using a PriorityQueue has the advantage of keeping the memory usage low (if the elements are large objects).

I know that DBs do this kind of trick.  However, their use case minimizes disk accesses whereas Streams are almost always used with in-memory objects.

Anyways, the issue is closed so I am not sure how much more this idea should be discussed.

**Comment by amaembo** [comment]
Actually this discussion led me to the thought that `least()/greatest()` should be improved first (see #70).

**Comment by nathanila** [comment]
Do you want to re-open this issue and make it dependent upon #70?  Once #70 is completed, you can then re-visit this idea.  Or do the other concerns still justify keeping this issue closed?

**Comment by amaembo** [comment]
Incompatibility with existing Stream API is still a major issue. It would be better to propose a patch to OpenJDK targeting to Java-9, though I doubt it will be accepted as it's quite complex (new non-trivial data structure, quite a lot of additional code which should be properly tested) and performance degradation is still possible in some cases...

**Comment by amaembo** [comment]
I finally submitted a patch to OpenJDK:

https://bugs.openjdk.java.net/browse/JDK-8153332

Chances to push this into Java-9 are not so big, but still not zero.
