### ISSUE TITLE
Add EntryStream.collapseKeys(): collapse adjacent elements with the equal key

### ISSUE THREAD

**Issue by amaembo** [amaembo/streamex#73]
Three signatures are proposed:

    // collapse elements with the same key gathering corresponding values to list
    EntryStream<K, List<V>> collapseKeys();

    // collapse elements with the same key reducing the values with given mergeFunction
    EntryStream<K, V> collapseKeys(BinaryOperator<V> mergeFunction);

    // collapse elements with the same key reducing the values with given Collector
    <A, R> EntryStream<K, R> collapseKeys(Collector<V, A, R> collector);

* [x] Implementation
* [x] Tests
* [x] JavaDoc
* [x] Changes
* [x] Cheatsheet

**Comment by lukaseder** [comment]
Interesting ideas.

I wonder if that version here:

```java
// collapse elements with the same key reducing the values with given mergeFunction
EntryStream<K, V> collapseKeys(BinaryOperator<V> mergeFunction);
```

... should perhaps rather look like this (or be overloaded with this):

```java
<U> EntryStream<K, U> collapseKeys(U seed, BiFunction<? super U, ? super V, ? extends U> function, BinaryOperator<U> mergeFunction);
```

The "default" implementation that collapses a key's values into a `List` would then be an obvious special case calling the above.

Also, have you thought about passing the key as well to the different collapse collectors? Perhaps, that could be useful for certain collapsing decisions...

**Comment by amaembo** [comment]
For this form

    <U> EntryStream<K, U> collapseKeys(U seed, BiFunction<? super U, ? super V, ? extends U> function, BinaryOperator<U> mergeFunction);

You can use `collapseKeys(Collectors.reducing(seed, function, mergeFunction))`. Actually `collapseKeys()` is the shortcut for `collapseKeys(Collectors.toList())` and `collapseKeys(op)` is the shortcut for `collapseKeys(collectingAndThen(reducing(op), Optional::get))`. Having dedicated version without a seed is important as meddling with optionals is absolutely unnecessary here (it's known that the result of reduction is never empty). But for seed-based version using `Collector` looks fine for me.

As for passing keys, if you really need it, you can always use `.chain(StreamEx::of).collapse((e1, e2) -> Objects.equals(e1.getKey(), e2.getKey()), (e1, e2) -> {merge function for entries})`. I don't think that it's useful enough to get its own shortcut (though if you have some real-life examples, you may post them). Especially taking into account that I still dislike adding non-standard functional interfaces to my library, so `(key1, value1, key2, value2) -> {...}` is not an option for me currently...

Actually I added this feature (along with #72) to complete the chain of moreless efficient fixed-length batching (using `headTail` is certainly an option, but it has more overhead). I really dislike adding features which parallelize badly and if I add them, they should be quite universal, so other badly parallelizable problems could be expressed as well. I was convinced to add zipping two streams (see #60). Now fixed-size batching is also possible with:

    Stream<T> stream = ... // stream to create batches from
    Stream<List<T>> batches = IntStream.ints()
               .flatMapToObj(x -> StreamEx.constant(x, batchSize))
               .zipWith(stream)
               .collapseKeys()
               .values();

While this looks quite verbose compared to possible dedicated method like (`.batches(batchSize)`), this is more flexible. For example, removing `.values()` you can have the batches automatically numbered. Also it's possible to create variable-length batches based on some condition. For example:

    Stream<List<T>> batches = IntStream.ints()
               .flatMapToObj(x -> StreamEx.constant(x, x))
               .zipWith(stream)
               .collapseKeys()
               .values();

Here we have increasing batch sizes (first List has size 1, second has size 2 and so on).

**Comment by lukaseder** [comment]
Thanks a lot for the feedback

> But for seed-based version using Collector looks fine for me.

You're right. I keep forgetting to look in the `Collectors` class for utilities.  I think we're following subtly different strategies with our libraries. StreamEx puts much more weight on the `Collector` type.

> I don't think that it's useful enough to get its own shortcut (though if you have some real-life examples, you may post them)

I don't, currently. I was just curious to see if you rejected that for a reason.

> I still dislike adding non-standard functional interfaces to my library

You can run, but you cannot hide :) You can always import `org.jooq.lambda.function.Function4`, too... and tuples, to avoid using `Map.Entry` ;)

Interesting batch examples. Is that all lazy, though? I.e. is the second / third batch already collected while the first is traversed?

**Comment by amaembo** [comment]
Of course, it's lazy. That's the whole point of partial reduction.

I hate tuples in Java :-) `Map.Entry` is the only thing I can tolerate and it's not generic tuple, it's assymetric (key and value have different meaning in general). That's why I added `collapseKeys()`, but not `collapseValues()`. Also other methods like `EntryStream.grouping()` are assymetric. But if you need more than two elements to keep together, in object-oriented language you should create a new class instead. With meaningful field names and useful methods. And possibly using primitive fields to avoid unnecessary boxing. Tuples seriously hurt the readability.

It looks like you are too SQL-minded :-) You're fine with tuples. That's ok, this means that our libraries will always be different and suitable for different people with different tastes.

**Comment by lukaseder** [comment]
Well, what can I say... :) Tuples are at the core of functional programming just the same as to SQL, which isn't so different from functional programming. But no worries, you don't have to add them. And even if you need a `Tuple3`, in principle you can still resort to "currying" them as `Entry<K1, Entry<K2, V>>`

Anyway, about partial reduction being lazy: I misunderstood your feature. I didn't catch the fact that you're collapsing only *adjacent* keys, not *all* equal keys (which can be the same thing if client code is in control of adjacency and ordering). That's quite cunning, and useful! Will shamelessly steal the idea :)
