### ISSUE TITLE
Implement EntryStream.removeKeyValue()

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#74]
EntryStream has a filterKeyValue(BiPredicate<? super K,? super V> predicate) but not a removeKeyValue(BiPredicate<? super K,? super V> predicate).  Please implement removeKeyValue().

**Comment by amaembo** [comment]
Thanks, implemented. For some reason I thought that it's already implemented. It was even added to [CHEATSHEET](https://github.com/amaembo/streamex/blame/769d73ce42d3608629a23fec8583be979a5b6bdf/CHEATSHEET.md#L53) several months ago.
