### ISSUE TITLE
Implement EntryStream.of(Iterator<V> iterator)

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#75]
Please add the following method to EntryStream: `public static <V> EntryStream<Integer, V> of(Iterator<V> iterator)`.  This method is similar to `public static <V> EntryStream<Integer, V> of(List<V> list)`.  With the addition of this method, one can take any Collection or Map and turn it into an indexed EntryStream.

**Comment by amaembo** [comment]
I don't want. Reasons:

* It's parallelized badly
* We should select the type of the indices: `Integer` or `Long`. `Iterator` is not constrained to have `Integer` size (while `List` is constrained).
* It can be expressed via `zipWith` easily and user can select, whether he wants integers or longs:

    IntStreamEx.ints().boxed().zipWith(StreamEx.of(iterator))
    LongStreamEx.longs().boxed().zipWith(StreamEx.of(iterator))

It's not very longer and gives user more control (see #60 and #72).
