### ISSUE TITLE
Back-port Java-9 three-arg Stream.iterate method and primitive friends

### ISSUE THREAD

**Issue by amaembo** [amaembo/streamex#79]
Three-argument method `Stream/IntStream/DoubleStream/LongStream.iterate` was [implemented by me](https://bugs.openjdk.java.net/browse/JDK-8072727) in Java-9 and currently [pushed](http://hg.openjdk.java.net/jdk9/jdk9/jdk/rev/9d2a7770ab23) to jdk9 branch. It would be nice to backport this to StreamEx as well. Seems that according to [Oracle Contributor Agreement](http://www.oracle.com/technetwork/oca-405177.pdf) I have rights just to copy the implementation to my project.

* [x] Implementation
* [x] Tests
* [x] JavaDoc
* [x] Changes
* [x] Cheatsheet

**Comment by lukaseder** [comment]
Hey, congrats for being a JDK contributor! Great to see your work being added, soon! How did that happen?

**Comment by amaembo** [comment]
@lukaseder it's a long story :-)

**Comment by lukaseder** [comment]
I have time :)

Any other stuff you're contributing? Do you have any influence, perhaps, on the unfortunate choice of naming of `dropWhile()` and `takeWhile()` (rather than the more consistent `skipWhile()` and `limitWhile()`)?

**Comment by amaembo** [comment]
> Any other stuff you're contributing? 

Use [search](http://hg.openjdk.java.net/jdk9/dev/jdk/log?rev=valeev).

> Do you have any influence, perhaps, on the unfortunate choice 

Nope, this feature was implemented long before my first contribution, so don't blame me!

**Comment by lukaseder** [comment]
Very nice, thanks for the link. I didn't blame you :)
