### ISSUE TITLE
Rename package javax.util.streamex

### ISSUE THREAD

**Issue by amaembo** [amaembo/streamex#8]
Using of javax package name is not recommended and actually against the [Oracle Binary Code License Agreement](http://www.oracle.com/technetwork/java/javase/terms/license/index.html), SUPPLEMENTAL LICENSE TERMS, F. Thus probably it would be good to change the package name in 0.5.0 version.

The package will be renamed to `one.util.streamex`, so existing users upon update will need to search-and-replace `javax.util.streamex` with `one.util.streamex` across the sources. Also the OSGi `Bundle-SymbolicName` will be changed to `one.util.streamex`, thus probably manifests should be changed as well. ~~No changes in Maven group ID/artifact ID will be applied~~. Maven group ID will be changed to `one.util` to stay in sync with package/OSGi name.

* [x] Register util.one
* [x] Update codebase (rename packages in main and test)
* [x] Update pom.xml to properly create OSGi manifest.
* [x] Request access to the `one.util` group ID on Maven Central.
* [x] Update pom.xml group ID.
* [x] Update README.md to warn about the change; probably add short migration guide.
* [x] Update README.md after 0.5.0 release to specify new group ID.
* [x] Add redirects from old documentation URLs (like `http://amaembo.github.io/streamex/javadoc/javax/util/streamex/StreamEx.html`) to new ones (like `http://amaembo.github.io/streamex/javadoc/one/util/streamex/StreamEx.html`) preserving the anchor.

**Comment by foal** [comment]
util.streamex :-1:

**Comment by amaembo** [comment]
@foal, thank you for your opinion. I discussed also with other people and now I'm more inclined to register a new domain.

**Comment by amaembo** [comment]
I registered http://util.one and the package will be renamed to `one.util.streamex`.

**Comment by amaembo** [comment]
I decided to change the Maven groupID as well to stay in sync with package/OSGi name and specify more clearly to the users that incompatible change (package renaming) was introduced.
