### ISSUE TITLE
Concurrent Stream

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#80]
I don't know if this is a good idea or not.  I had implemented something like this a long time ago before Stream was introduced in Java 8.  So, I offer the idea for your consideration.

Today, Streams are either single-threaded sequentially executed or multi-threaded executed in parallel.  In the latter case, all threads execute the entire or at least most of the stream stages (e.g. map, filter, etc).

Consider a third type of stream: concurrent.  Like parallel, this stream employs multiple threads.  However, each thread executes a single stage.  The thread pulls data from a queue from the previous stage, processes the data and pushes the data into a queue for the next stage.  This kind of stream makes sense if each stage is doing a lot of work compared to the time to pull and push on a queue.

This kind of stream allows for the processing inside a stage to be stateful.  The state is only manipulated by one thread and hence no locking is required.

Will we need 1 thread per stage?  No.  One stage is typically the bottleneck.  Hence, a thread will be dedicated towards processing in that stage.  There will be 1 or more threads to execute all of the other stages.

**Comment by lukaseder** [comment]
(not officially answering here): How does that compare to something like actor models, and other message processing systems?

**Comment by amaembo** [comment]
Thank you for your suggestion. Unfortunately currently I'm not interested in such feature. You may try to explore other libraries for such functionality (probably RxJava can do something like this?)
