### ISSUE TITLE
Eclipse Compiler vs Javac

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#81]
The following code compiles just find with the Eclipse IDE compiler.  However, `javac` can't compile it.

```
StreamEx.
   iterate(clazz, cls -> (Class) cls.getSuperclass()).
   takeWhile(Objects::nonNull).
   map(Class::getDeclaredFields);
```

Here is the error message from `javac`.

```
<R>map(java.util.function.Function<? super T,? extends R>) in one.util.streamex.AbstractStreamEx is defined in an inaccessible class or interface
```

It seems that `javac` isn't able to resolve the generic return type of `takeWhile()`.

**Comment by nathanila** [comment]
Here is the workaround.

```
StreamEx<Class<?>> classStream;

classStream = StreamEx.
   iterate(clazz, cls -> cls.getSuperclass());

classStream = classStream.
   takeWhile(Objects::nonNull);

classStream.
   map(Class::getDeclaredFields);
```

**Comment by nathanila** [comment]
I don't know if `javac` is too strict or if Eclipse IDE compiler is too loose on the implementation.  Either way a bug should be filed against `javac` or Eclipse IDE compiler.  If `javac` is correct in the implementation, then the `StreamEx` library definitely should be adjusted.  If `javac` is incorrect, then please consider changing the `StreamEx` library.

**Comment by amaembo** [comment]
Note that you are using the raw type `Class`. Using raw types is almost always bad idea. In any case it does not worth fixing the compilation of code involving raw types. Try these variations:

    StreamEx.
       iterate(clazz, cls -> (Class<?>) cls.getSuperclass()).
       takeWhile(Objects::nonNull).
       map(Class::getDeclaredFields);

And (better)

    StreamEx.<Class<?>>
       iterate(clazz, cls -> cls.getSuperclass()).
       takeWhile(Objects::nonNull).
       map(Class::getDeclaredFields);

Also which javac version are you using?

**Comment by nathanila** [comment]
The first case didn’t work.  The second case worked!  Using <Class<?>> always gets me.

 

I am using Java version…

 

java version "1.8.0_73"

Java(TM) SE Runtime Environment (build 1.8.0_73-b02)

Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

 

-Nathan

**Comment by amaembo** [comment]
I edited the message after posting it (fixing the first case). It seems that you've answered to the e-mail notification which shows the first version of the post. `StreamEx.iterate(clazz, (Class<?> cls) -> cls.getSuperclass()).` should work as well.
