### ISSUE TITLE
StreamEx.of() methods should accept collections with covariant generic type <? extends T>

### ISSUE THREAD

**Issue by lukaseder** [amaembo/streamex#83]
For example, instead of:

```java
public static <T> StreamEx<T> of(Collection<T> collection)
```

write:

```java
public static <T> StreamEx<T> of(Collection<? extends T> collection)
```

The advantage is, for instance, to be able to do things like these:

```java
List<Integer> integers = Arrays.asList(1, 2, 3);
StreamEx<Number> numbers = StreamEx.of(integers);
```

If Java already had declaration-site variance, you'd declare `interface StreamEx<out T>`, in case of which you'd get this functionality for free, but short of declaration-site variance, we have to explicitly allow variance on every method.

**Comment by amaembo** [comment]
Stream is rarely assigned to the variable, but it could be useful sometimes, e.g. when due to contract you need to return `StreamEx` of more abstract type from some method (when implementing interface/abstract class). Fixed, thanks.
