### ISSUE TITLE
Add support to simplify Exceptions processing

### ISSUE THREAD

**Issue by foal** [amaembo/streamex#84]
Inspired by http://slieb.org/blog/throwable-interfaces

**Comment by amaembo** [comment]
Sorry, this feature is out of the scope of my library. Motivation:

* Handling exceptions in lambdas is not directly connected to the Stream API and my library enhances Stream API only, it does not extend everything in Java-8.
* There are many functional interfaces and for all of them should throwing alternatives should be provided which would significantly increase number of public classes.
* There are too many possible solutions for this problem. Swallow exception (should we swallow RuntimeException and Error as well?)? Rethrow it as unchecked (which unchecked type exactly should be used? `UncheckedIOException` for `IOException`? What about `SQLException` and others?)? Provide default behavior (like when filter `Predicate` throws, return `false` instead)? Adopt `Try` monad?

I guess, there are plenty alternative solutions available. Also it's not very hard to code it by yourself.  You can use whatever is best suitable in your case.

I personally stick with explicit try-catch block when (quite rare) hit this problem. Also I avoid defining my own checked Exceptions.
