### ISSUE TITLE
Publish AbstractStreamEx class

### ISSUE THREAD

**Issue by amaembo** [amaembo/streamex#90]
Currently some methods are defined in the `AbstractStreamEx` class which is package-private. This limits the possibilities to use method references with javac <8u102 (see [JDK-8143647](https://bugs.openjdk.java.net/browse/JDK-8143647)). Seems that ECJ also sometimes compiles such references incorrectly. Here's testcase which fails:

~~~~java
List<String> input = asList("a", "b", "c");
assertEquals(input, input.stream().map(StreamEx::of).reduce(StreamEx::append).get().toList());
~~~~

When compiling with javac:

    java.lang.IllegalAccessError: one/util/streamex/AbstractStreamEx

When compiling with ecj:

    java.lang.NoSuchMethodError: one.util.streamex.StreamEx.append(Ljava/util/stream/Stream;)Lone/util/streamex/StreamEx;

Seems that it's possible to make `AbstractStreamEx` public which would also solve some javadoc-related issues and compilation errors in some corner cases (like reported in #81). If you have better idea for its name, you're welcome.

* [x] Write AbstractStreamEx class JavaDoc
* [x] Make it public
* [x] Deduplicate `chain` method
* [x] Provide at least some tests from another package which validate this change (see also #91)
* [x] Changes

**Comment by lirikooda** [comment]
I'm seeing the something similar with code compiled with `kotlin` (1.7.10).
Calling a StreamEx `.distinct()` works fine, but `.distinct(java.util.function.Function)` fails with `NoSuchMethodError`.
Any idea?

**Comment by amaembo** [comment]
Please provide a link to a minimal project that illustrates the problem. Thanks. Likely a Kotlin compiler problem.
