### ISSUE TITLE
StreamEx of Cartesian product

### ISSUE THREAD

**Issue by KidCrippler** [amaembo/streamex#96]
StreamEx::zip generates a StreamEx of 2 lists' pairs when taking their respective indices into account.
I thought it would be nice to have a similar method (StreamEx::cross maybe?) that does the same, but generates a StreamEx of pairs of the lists' cartesian product.

**Comment by amaembo** [comment]
Use `StreamEx.of(list1).cross(list2)` and you will get an `EntryStream` of `list1` and `list2` cartesian product. If you want to convert `EntryStream` back to `StreamEx`, use `StreamEx.of(list1).cross(list2).mapKeyValue((itemFromList1, itemFromList2) -> mergeThemSomeHow)`.

An alternative (if `list1` and `list2` element types are the same) is to use `StreamEx.cartesianProduct(Arrays.asList(list1, list2))` which will produce a `StreamEx<List<ElementType>>` (stream of two-element lists). 

You can also use `StreamEx.cartesianProduct` with accumulator function. For example, for two lists of strings to concatenate possible pairs: `StreamEx.cartesianProducts(Arrays.asList(list1, list2), "", String::concat)`. Using `cartesianProduct` methods you are not limited to two lists.

**Comment by KidCrippler** [comment]
Turns out I was using an old version which doesn't have this functionality.
10x
